### ISSUE TITLE
Container id instead of host in file upload URL

### ISSUE THREAD

**Issue by lkostrowski** [strapi/strapi-docker#10]
**Node.js version**:
https://github.com/strapi/strapi-docker 
(v9.8.0)

**npm version**:
https://github.com/strapi/strapi-docker
(5.6.0)

**Strapi version**:
https://github.com/strapi/strapi-docker
(3.0.0-alpha.11)

**Operating system**:
Docker

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
After photo gets uploaded URL is copied to clipboard:
http://cb63deeba9d8:1337/uploads/3a92cc8f08394d35bfa5bccd867c9f6c.JPG

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1: Upload file
2: Click on entry

**What is the expected behavior?**
url should start with "localhost" or domain name

---

"cb63deeba9d8" is id of a container.

I assume ENV with host should be provided

**Comment by lucaperret** [comment]
`HOST` environment variable should be provided via the docker-compose.

**Comment by lkostrowski** [comment]
Works, will do PR to readme in the evening

**Comment by lucaperret** [comment]
Could you add it in the docker-compose.yml ?
No need to put it in the README, this value isn't relevant to configure because should always be `localhost` when Strapi is launch within docker-compose.

**Comment by lkostrowski** [comment]
Sure

**Comment by dkarski** [comment]
@lucaperret why should be `localhost`, so how to change `host` to some domain name where application is hosted? File plugin output url reference by localhost then domain.
