### ISSUE TITLE
Possibility to run custom scripts on startup

### ISSUE THREAD

**Issue by botzill** [strapi/strapi-docker#102]
Hi.

I was wondering if you plan to add some custom scripts that can be plug in and run after the app was started. Such a script could create automatically api via `strapi generate:api` or any other command. This way we can easily startup with already defined resources types. If you plan to add such feature I can make PR. 

Let me know what you think about it.

**Comment by lauriejim** [comment]
Hello!
The feature you need is powered by the `./config/bootstrap.js` file.
This function is called just before the start of the server. In this function you will access to all the Strapi application functions.
Hop it help.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Comment by BriantAnthony** [comment]
I thought I should also mention that you can run custom scripts on-demand by running:
`strapi.config.functions['fileName']();`

You should have the strapi console running prior to this with:
`yarn strapi console`

This allows you to run scripts that do things like normalize all data, export data to an external source, or anything that would not be appropriate to add inside an endpoint.

**Comment by dzcpy** [comment]
How about V4? Is it the same?

**Comment by VadimGut** [comment]
> 

It is a bit different
checkout the [docs here](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/functions.html#bootstrap)
