### ISSUE TITLE
Unable to load data after container restart

### ISSUE THREAD

**Issue by CMatias** [strapi/strapi-docker#106]
So, my admin panel was throwing some error and leaving Strapi unusable so I rebuilt the containers (`docker-compose down && docker-compose up -d`).

Upon restart I needed to create a new admin user and all the data previously inputted was lost. The data still lies in the `db` volume but the strapi database created in mongo is empty. The content-types are also loading properly.

My docker-compose file is the latest one.

Any idea on how to load back the data? Thanks in advance

**Comment by mmoustai** [comment]
I had the exactly same issue yesterday.

I added some log. Hope this can help debugging us.

`TypeError: Cannot read property '_id' of null
    at module.exports (/usr/src/api/strapi-app/plugins/users-permissions/config/policies/permissions.js:51:16)`

`Stopping strapi
(node:18) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

(node:18) UnhandledPromiseRejectionWarning: MongoError: Failed to parse: { find: "core_store", filter: { key: "plugin_users-permissions_grant", environment: "", tag: "" }, projection: {}, limit: 1, singleBatch: true, batchSize: 1, returnKey: false, showRecordId: false, lsid: { id: BinData(4, 6F84DB90EFF047AF84592690E00CA598) } }. Unrecognized field 'lsid'.
    at queryCallback (/usr/src/api/strapi-app/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /usr/src/api/strapi-app/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at process.internalTickCallback (internal/process/next_tick.js:70:11)

(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:18) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at fs.readdir (/usr/src/api/strapi-app/plugins/upload/config/functions/bootstrap.js:55:40)
    at _tickCallback (internal/process/next_tick.js:43:7)
    at processImmediate (timers.js:605:7)
    at process.topLevelDomainCallback (domain.js:120:23)

(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

(node:18) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.

[2019-03-26T17:32:49.402Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
[2019-03-26T17:32:49.402Z] warn Perhaps you forgot to call it?
Stopping strapi

(node:18) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

(node:18) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.

(node:18) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead

(node:18) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.`

The api was working without any problem. This appeared suddenly.

I updated to the last version, starting again and had the same problem again.

**Comment by CMatias** [comment]
I was unable to grab that log but can confirm it was the same problem.

**Comment by lauriejim** [comment]
What is the Strapi version you use please.

**Comment by CMatias** [comment]
@lauriejim 
```
"strapi": "3.0.0-alpha.23.1",
"strapi-hook-mongoose": "3.0.0-alpha.23.1"
```

**Comment by janober** [comment]
More or less same issue here. Everything I created yesterday is somehow lost today.

(Current docker-compose file with Strapi v3.0.0-alpha.26.2 on Ubuntu 18.04.2)

**Comment by janober** [comment]
Update: Interestingly it is back now?!?! Created a new admin-user and DataType to test another issue I had. Then turned everything off with "docker-compose stop" and started it again with "docker-compose up" and the data from yesterday was back. Now however the test-data from just before is gone but I am OK with that.

**Comment by songoten28** [comment]
You change like this if you want to keep data
`    db:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD = postgres
    ports:
      - 5432:5432
    volumes:
     - "database_volume:/var/lib/postgresql/data"
    restart: always
volumes:
  ? database_volume`

or change like this

` volumes:
     - "./db:/var/lib/postgresql/data"
`
This way just for purpose for test.

**Comment by CMatias** [comment]
@songoten28 The problem was not that the data was lost (data deleted from the database) but rather that Strapi wasn't able to fetch data from the database.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Comment by santhosh-scalex** [comment]
i have deployed my strapi on ecs fargate , whenever my container restarted the data is lost ? can you suggest any better way to resolve this
