### ISSUE TITLE
Azure deployment with Azure Container Instance halted by "Installer" process

### ISSUE THREAD

**Issue by RedactedProfile** [strapi/strapi-docker#110]
Trying to deploy a basic `strapi/strapi` image via Azure Container Instance, with this command

(connection values redacted for obvious reasons)
`az container create --resource-group csg --name csgcms --image strapi/strapi --restart-policy OnFailure --environment-variables "APP_NAME"="CMS" "DATABASE_HOST"="***.***.***.***" "DATABASE_PORT"="3306" "DATABASE_NAME"="***" "DATABASE_USERNAME"="***" "DATABASE_PASSWORD"="***"`

And while everything deployed just fine, the container immediately started rolling and falling back and restarting several times.  Checking the logs I was greeted with this:

```
C:\Users\Owner>az container logs --resource-group csg --name csgcms
🚀 Starting to create your Strapi application.

? Choose your installation type (Use arrow keys)
❯ Quickstart (recommended)
  Custom (manual settings) [27D[27C
```

Is it at all possible to allow feeding the "installer" all the right information passed to it via environment variables for an initial setup on first container run?  I work on a laptop that cant run VM's so I cant just pull down the image and customize it myself

**Comment by lauriejim** [comment]
Hello!

You forgot the `DATABASE_CLIENT`

**Comment by RedactedProfile** [comment]
@lauriejim by jove, you're right 

Im 1000% positive I had the database client env var in there at some point but must have got missed in the move to using the azure cli.  

Thank you, I will give this a shot

**Comment by lauriejim** [comment]
Okay great! Let me know to close this issue.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
