### ISSUE TITLE
Npm run setup

### ISSUE THREAD

**Issue by MatteoGioioso** [strapi/strapi-docker#111]
Looks like is not possible to run `npm run setup` with the current setup, I have tried to modify the script by adding:
```
if [ ! -f "$APP_NAME/package.json" ]
then
 ...
elif [ ! -d "$APP_NAME/node_modules" ]
then
    npm install --prefix ./$APP_NAME
fi

cd $APP_NAME &&
npm run setup &&
strapi start &

strapiPID=$!
wait "$strapiPID"
```

but no luck, the strapi container crash at start time
```
 exec user process caused "no such file or directory" 
```

Any suggestions?

**Comment by MatteoGioioso** [comment]
up!

**Comment by lauriejim** [comment]
Hello! Never tried and I haven't the time for now.
Hop the Strapi community can help you on this point.

**Comment by dkarski** [comment]
@MatteoGioioso I tried localy run script with setup command and it's work. Could you share your complete script?

`$APP_NAME` is defined?

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
