### ISSUE TITLE
Container fails to start due to existing database

### ISSUE THREAD

**Issue by icarlosmendez** [strapi/strapi-docker#117]
I have set up strapi successfully via a docker-compose.yml file. Below you can see the service definitions for the two services in question.

postgres_server:
    build:
      context: ./postgres_server/
      dockerfile: postgres.Dockerfile
    image: postgres_server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: testdb
      # PGPASSWORD: psqlpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  strapi_api:
    build: 
      context: ./strapi_cms/
      dockerfile: strapi.Dockerfile
    image: strapi_server
    environment:
      - APP_NAME=my-app-template
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres_server
      - DATABASE_PORT=5432
      - DATABASE_NAME=testdb
      - DATABASE_USERNAME=dbuser
      - DATABASE_PASSWORD=dbpass
      - DATABASE_SSL=false
      # - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - postgres_server
    restart: always

Upon initial launch I successfully utilized the strapi app to add some simple content to my db. While testing I executed a docker-compose down && docker-compose up --build. During the rebuild/restart phase I am faced with the following error with no way of responding to the question of whether I want to continue with the existing database.

`strapi_api_1       | 🤔 It seems that your database is not empty. Be aware that Strapi is going to automatically creates tables & columns, and might update columns which can corrupt data or cause data loss.
strapi_api_1       | ? Are you sure you want to continue with the testdb database: (Y/n)`

I would like to simply submit Yes to the question but my terminal continues to post messages from other services and I can not respond to the query. Is there a way to hardcode this response in the Dockerfile or via an environment variable in the compose file to prevent this failure?

Any assistance will be greatly appreciated. 
Merci!

**Comment by icarlosmendez** [comment]
Some additional information regarding this issue and possible solutions:
I managed to pause the service which was generating tons of console information to try and give myself a chance to respond to the query and the pause was successful. 
But as you can see below, the container or the application itself is restarting pretty much immediately once the query presents.

`my-app-template_strapi_api_1 exited with code 130`
`strapi_api_1       | 🚀 Starting to create your Strapi application.`
`strapi_api_1       | `
`strapi_api_1       | Database determined by CLI args: postgres`
`strapi_api_1       | `
`strapi_api_1       | ⏳ Testing database connection...`
`strapi_api_1       | It might take a minute, please have a coffee ☕️`
`strapi_api_1       | 🤔 It seems that your database is not empty. Be aware that Strapi is going to automatically creates tables & columns, and might update columns which can corrupt data or cause data loss.`
`strapi_api_1       | ? Are you sure you want to continue with the testdb database: (Y/n) y`
`my-app-template_strapi_api_1 exited with code 130`

 I did even manage to time my response and squeezed a 'y' in there but the container exited anyway.

Thanks again for your consideration.

**Comment by lauriejim** [comment]
Hello! 

You can add `--dbforce` option in your `strapi new` command.
📚Documentation here https://strapi.io/documentation/3.x.x/cli/CLI.html#strapi-new
In the docker config there is an option for extra argument like this one.

> Can you please take care about your message format and a good usage of markdown
> I read hundred issue per day and it help me to have clean messages.

**Comment by msreekm** [comment]
where do we add --dbforce when you are runinnig in docker container?  is that a env variable?
