### ISSUE TITLE
GraphQL plugin restart cycle due Strapi version

### ISSUE THREAD

**Issue by diegoTiscareno** [strapi/strapi-docker#119]
Using this image as a base to run an existing Strapi project using the GraphQL plugin seems to be incompatible. I ran into an issue where Strapi keept trying to restart the application due to detected changes in the generated GraphQL schemas:

```
[2019-05-28T21:55:29.126Z] info File changed: /usr/src/api/myapi/plugins/graphql/config/generated/schema.graphql
[2019-05-28T21:55:29.129Z] info The server is restarting

[2019-05-28T21:55:32.564Z] info File changed: /usr/src/api/myproject/plugins/graphql/config/generated/schema.graphql
[2019-05-28T21:55:32.565Z] info The server is restarting

...
```

After poking around at the issue, I found that [this](https://github.com/strapi/strapi/blob/master/packages/strapi/bin/strapi-start.js#L55) line in the Strapi project doesn't exist yet in the [version being installed in the image](https://github.com/strapi/strapi-docker/blob/8d87ec44d79f378ae12d823f1cdeb062aa69efd7/Dockerfile#L16)

I worked around this by installing the latest version in my Dockerfile:

```Dockerfile
FROM strapi/strapi
RUN npm install -g strapi@1.6.4
...
```

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
