### ISSUE TITLE
Problem using lifecycle callback

### ISSUE THREAD

**Issue by mogensgrosen** [strapi/strapi-docker#126]
Hi. I am relatively new to strapi and have a problem using (or understanding) life cycle callback. 
I have a simple use case: the user enter income1 and income2 and afterwards calculates and stores total as the sum of income1 and income 2. 
What I did:
I installed strapi using the the quick-start option. 
I created a model with income1, income2 and total
I inserted the following code in beforesave lifecycle callback (used for update and insert)

   beforeSave: async (model, attrs, options) => {

    attrs.total = attrs.income1 + attrs.income2;

    console.log( "before save income1: ", attrs.income1);
    console.log( "before save income2: ", attrs.income2);
    console.log( "before save total: ", attrs.total);
    
   },

When inserting a row I get following error (from the log)
before save income1:  10
before save income2:  10
before save total:  20
before save income1:  undefined
before save income2:  undefined
before save total:  NaN

And the the total do not get stored. When I update a row it works.

I have read this post about using life cycle callback (called twice), but it is still very unclear to me how to use lifecycle callbacks
https://github.com/strapi/strapi/issues/1153

Please advise me on how to do simple calculations and storing data using lifecycle callback.

**Comment by lauriejim** [comment]
Hello! Yes there is issues with the way life cycle is used in Strapi.
The first call is to create the entry and the second for the update of relations (even if you don't have relations)
I suggest you to add a condition to make sure your `income1` and `income2` exist before updating your `total` attribute.

**Comment by mogensgrosen** [comment]
Hello lauriejim
I still have a problem on creating simple calculated field. 

I changes the beforeSave to this
beforeSave: async (model, attrs, options) => {

    if (attrs.income1 != undefined) {
       attrs.total = attrs.income1 + attrs.income2;
     }

    console.log( "before save income1: ", attrs.income1);
    console.log( "before save income2: ", attrs.income2);
    console.log( "before save total: ", attrs.total);
    
   },

And I get the following result when inserting: 
before save income1:  50
before save income2:  50
before save total:  100
before save income1:  undefined
before save income2:  undefined
before save total:  undefined

Total do not get stored. Update works. 

Please guide me on how and where to add condition on whether income1 and income2 exists in order to have update and insert working properly.

**Comment by lauriejim** [comment]
Ho okay!
In fact the log value doesn't affect the cause before your value is not saved in your database on the creation.
It's because if you don't send `total` attribute in the request, you will not be able to update it.
When you send the create data, you don't send `total` attribute. So you can't update it.
In the update, the `total` is sent as `null` value. This is the reason why you are able to update it.

So to deal with that and to don't have to manually add 0 to the total input every time (to send a random value, just to be able to update it in the create function), I suggest you to go in the content type builder and edit the `total` attribute and set a default value.

**Comment by mogensgrosen** [comment]
Hello again
I tried to insert 0 in the total field (manually and default value) and I get the same result: Total is not inserted. When updating a record it works. Please guide me.
