### ISSUE TITLE
Increase Docker Health Check Startup Length

### ISSUE THREAD

**Issue by brandonhudson** [strapi/strapi-docker#130]
Hello,

I recently deployed Strapi to our Swarm cluster as a service and was running into health check issues where the service was killing the containers prior to it fully starting up. The container was taking longer than 30 seconds to start, and the health check timer was being tripped.

As such, I'm recommending increasing the health check start time (here: https://github.com/strapi/strapi-docker/blob/master/Dockerfile#L24) to something greater than 30 seconds. I modified the Dockerfile to include a 5m startup timeout and published it to our internal registry and it resolved the issue completely.

**Comment by brandonhudson** [comment]
Happy to submit a PR for this if you'd like. Just wanted to gauge thoughts prior to doing so.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
