### ISSUE TITLE
Database password file ENV var

### ISSUE THREAD

**Issue by jimdesalvo** [strapi/strapi-docker#132]
Allow the DB password to be set from a file so docker secrets can be leveraged and keep it from being exposed in a docker inspect.  Similar to the functionality found in the Wordpress official image.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Comment by agramian** [comment]
Was adding docker secret support addressed in the docker image rebuild mentioned above or should this be reopened as a new pr?

**Comment by ChrisKatsaras** [comment]
I'm curious about this as well. @jimdesalvo did you end up figuring out a solution? @alexandrebodin do you have any suggestions about how to use Docker secrets with our `database.json` files?

**Comment by alexandrebodin** [comment]
Hi, right now I would suggest you use this example https://stackoverflow.com/questions/59792344/strapi-cms-where-to-put-the-environment-variables to setup `.env` support. Once it is setup you can create a docker secret for the `.env` file :). 

In an upcoming release we are planning to support .env files natively so you will have less work to do. 

Hopefully this helped you :) Let me know ;)

**Comment by ChrisKatsaras** [comment]
Thanks for the quick response! This is an interesting solution but still requires a `.env` file. Unless I'm misunderstanding, there's no way to create a `docker secret` and then read it from our `database.json` file? I'm just a bit confused about how `docker secret` can be used in the example above.

**Comment by alexandrebodin** [comment]
I haven't used docker secret but from what I understood a secret is shared to the container in a file. So this would be easy to set the secret as the content of the .env file and when running the container share this secret as a .env file in the project folder so it is used.

**Comment by ChrisKatsaras** [comment]
That makes sense! Thanks for your help @alexandrebodin  🎉

**Comment by dargmuesli** [comment]
I configured `/config/database.js` manually to load the database's user and their password from Docker secrets:

```javascript
const fs = require('fs');

const secretPostgresPasswordPath = '/run/secrets/postgres_password'
const secretPostgresUserPath = '/run/secrets/postgres_user'

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', 'postgres'),
        port: env.int('DATABASE_PORT', 5432),
        database: env('DATABASE_NAME', 'strapi'),
        username: env('DATABASE_USERNAME', fs.readFileSync(secretPostgresUserPath, 'utf-8')),
        password: env('DATABASE_PASSWORD', fs.readFileSync(secretPostgresPasswordPath, 'utf-8')),
        ssl: env.bool('DATABASE_SSL', false),
      },
      options: {}
    },
  },
});
```

**Comment by trevthewebdev** [comment]
@dargmuesli I assume this configuration works? This is the actual answer to the question though reading files synchronously, especially if you have even a handful of secrets, can be much slower.

@ChrisKatsaras @alexandrebodin the trick with docker secrets, as you can see in @dargmuesli's example, is that they are in the container's file system which means they have to be read in order to be used. It would then not be easy to read them all, and put them into an .env before strapi attempts to starts and fails do to missing env data.

It looks like it might be possible to load up all environment variables via the bootstrap function and then set them into the process.env object. https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#bootstrap

**Comment by dargmuesli** [comment]
Yep, I'm still using that. But regarding the `ADMIN_JWT_SECRET` used in `server.js` it looked to me like that couldn't be set using `fs` as that wasn't available for use there.

**Comment by trevthewebdev** [comment]
@dargmuesli thanks for the insight, I did a little more digging, I haven't tried it yet but I think we can read the files into memory during the bootstrap function and set them for use in other areas of the code. Will let you know once I've had a chance to try it out.

**Comment by alan-nicolas** [comment]
Hi! A bit late to the party. But for any wandering/lazy souls, here's how you could set env vars to docker secrets using the bootstrap api at `./config/functions/bootstrap`:

```js
async function setEnvVarsFromDockerSecrets() {
  // iterate over all env vars
  Object.keys(process.env).forEach((envName) => {
    if (!envName.endsWith("_FILE")) return;

    let pathToSecret = process.env[envName];

    // either empty or isn't path to secret
    if (!pathToSecret || !pathToSecret.startsWith("/run/secrets/")) return;

    // read first line only, ignore the pesky new-line character
    const secret = fs.readFileSync(pathToSecret, { encoding: "utf8" }).trim();

    // et voilà !
    const properEnvName = envName.replace(/_FILE$/, "");
    process.env[properEnvName] = secret;
  });
}

// AND of course, don't forget to call that in the exported bootstrap function.
// Probably as soon as possible :)
module.exports = async () => {
  setEnvVarsFromDockerSecrets();
  // ...
}
```

@trevthewebdev , thank you for mentioning the bootstrap idea! I had barely glanced at the docs. :P

**Comment by dargmuesli** [comment]
Hey @alan-nicolas, I tried that for the `ADMIN_JWT_SECRET` but unfortunately it seems like `server.js` is invoked before `bootstrap.js` and thus cannot initialize `ADMIN_JWT_SECRET` 😕

**Comment by alan-nicolas** [comment]
> Hey @alan-nicolas, I tried that for the `ADMIN_JWT_SECRET` but unfortunately it seems like `server.js` is invoked before `bootstrap.js` and thus cannot initialize `ADMIN_JWT_SECRET` confused

Oh! So sorry for that. I was testing this setup to create an admin user on boot and it worked. But I doubled check and indeed, it does not work for ADMIN_JWT_SECRET, as `server.js` runs prior to bootstrap.

However, I just tested it, and I can access the secret from `server.js` using the `fs` module. Now, that is a bit ugly, but you can. I'm gonna code it, double check it, and get back to you! I should think that the ADMIN_JWT_FILE env var should be available also, since we're setting that up from docker and thus sidestepping the bootstrap-prior-to-server-config thingy! :)

**Comment by alan-nicolas** [comment]
@dargmuesli Something like this? If I don't come back yelling fire, it means I got it to work!

```js
module.exports = ({ env }) => {
  let jwtSecret;
  // here we should refine the logic. And all this seems ripe for being
  // abstracted into its own utility file!
  if (process.env["ADMIN_JWT_SECRET_FILE"]) {
    try {
      // We read the secret as configured with the _FILE suffix
      jwtSecret = fs
        .readFileSync(process.env["ADMIN_JWT_SECRET_FILE"], {
          encoding: "utf8",
        })
        .trim();
      // JACKPOT! We set the proper env var
      process.env["ADMIN_JWT_SECRET"] = jwtSecret;
    } catch (err) {
      console.log("Failed while trying to read ADMIN_JWT_SECRET_FILE");
      console.log(err);
    }
  }

  return {
    host: env("HOST", "0.0.0.0"),
    port: env.int("PORT", 1337),
    admin: {
      auth: {
        secret: env("ADMIN_JWT_SECRET", "f609564c9fc6960649d5f3b79b41620a"),
      },
    },
  };
};
```

**Comment by dargmuesli** [comment]
Well, last time I checked, `fs` was not available from `server.js`. Did that change?

**Comment by alan-nicolas** [comment]
@dargmuesli Oh, I see! Yes, then it must have changed. That code I posted works for me with 3.4.6. :smiley:

**Comment by dargmuesli** [comment]
Yes, this actually seem to work now, nice!
