### ISSUE TITLE
 Database connection has failed! Make sure your database is running.

### ISSUE THREAD

**Issue by ngprnk** [strapi/strapi-docker#133]
**Describe the bug**
Error
` Database connection has failed! Make sure your database is running.`

**Steps to reproduce the behavior**
Please see the  Dockerfile below.
1. docker build -t strapi .
2. docker run -p 3000:3000 strapi:latest

**Expected behavior**
Should work
**Screenshots**
<img width="1007" alt="Screen Shot 2019-08-03 at 1 55 18 PM" src="https://user-images.githubusercontent.com/5570651/62407107-6609a080-b5f6-11e9-91cf-4909e5972e9c.png">

**Code snippets**
Docker File content
```yml
FROM strapi/strapi
ENV DATABASE_CLIENT=mongo
ENV DATABASE_HOST=strapi-mongo
ENV DATABASE_PORT=27017
ENV DATABASE_NAME=db
ENV DATABASE_USERNAME=db
ENV DATABASE_PASSWORD=db
ENV DATABASE_SRV=FALSE
ENV DATABASE_SSL=FALSE
ENV DATABASE_AUTHENTICATION_DATABASE=db

```
**System**
Docker

**Comment by ngprnk** [comment]
None of the provided solutions worked for me so i rolled a custom one 

```
FROM node:10.15.3
WORKDIR /app
COPY package.json /app

COPY . /app
RUN npm install strapi@beta -g
RUN npm install
CMD strapi develop
EXPOSE 1337
```

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
