### ISSUE TITLE
Once new content type is created, cannot enable WYSIWYG for fields.

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi-docker#137]
**Describe the bug**
Once new content type is created, cannot enable WYSIWYG when you edit text field.
I tested with both following general installtaion using `npm install -g strapi` and `getstarted` example in this repository.

**Steps to reproduce the behavior**
1. Go to Content Type Builder menu.
2. Add new content type with default setting (just name)
3. Add `text` field with default setting (just name)
4. Click save.
5. After server is restarted, go to Content Type Builder again.
6. Edit the `text` field, go to advanced setting.
7. Check to enable WYSIWYG.
8. Click Save, and save again.
9. After restarting, WYSIWYG is not enabled at all.

**Expected behavior**
WYSIWYG should have enabled when you edit content type.

**System**
- Node.js version: v10.15.3
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.14
- Database: tested both in SQLite and MySQL
- Operating system: macOS Mojave

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
