### ISSUE TITLE
Error when trying to run containers on bridge network

### ISSUE THREAD

**Issue by Gerche** [strapi/strapi-docker#139]
I'm new to docker and I am trying to connect my front-end (also running in a docker container) to strapi. To do so I believe they should run on the same docker network. I've tried adding `network_mode: bridge` to both my services in the docker-compose.yml file to run them in the same network as my front-end.

However for some reason I now get the following error:
`
api_1  | [2019-08-19T19:54:51.976Z] debug ⛔️ Server wasn't able to start properly.
api_1  | [2019-08-19T19:54:51.976Z] error Make sure your MongoDB database is running...
api_1  | Make sure your MongoDB database is running...
`

the logs of db_1 don't show an error and I see: `waiting for connections on port 27017`.
All containers are running (`docker ps`) and if i inspect my bridge network i do see all three services.
I'm not sure why running the db on a different network prevents it from starting, is this a bug or am I perhaps missing something else? If I run it without `network_mode: bridge` it runs just fine but my front-end container can't connect.

my docker-compose.yml file:

```version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always
    network_mode: bridge

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
    network_mode: bridge
```

**Comment by izzuddinnatsir** [comment]
Try to move db service/container as the first service and api service as the second

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
