### ISSUE TITLE
Admin panel running on wrong port in Docker on MacOS

### ISSUE THREAD

**Issue by GPavlovic** [strapi/strapi-docker#140]
When I run Strapi within Docker on MacOS, the admin panel seems to run under a different port than usual (on Windows the port is 1337 as expected). This is a clean image, I haven't changed any of the config. Any idea what could be wrong?

![Screen Shot 2019-08-27 at 6 58 22 PM](https://user-images.githubusercontent.com/5474337/63814070-a4e0fc80-c8fd-11e9-9b9a-e32cefac753f.png)

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
