### ISSUE TITLE
azure container instance + postgres fails Testing database connection...database overwrite warning

### ISSUE THREAD

**Issue by msreekm** [strapi/strapi-docker#146]
Get this error ,but I cannot confirm that since it is in docker image , how do I pass a env variable to default to yes and does this mean everytime a container is stopped and restarted ,data is lost? 
Testing database connection...
It might take a minute, please have a coffee ☕️
🤔 It seems that your database is not empty. Be aware that Strapi is going to automatically creates tables & columns, and might update columns which can corrupt data or cause data loss.
? Are you sure you want to continue with the XXX-CMS database: (Y/n)

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
