### ISSUE TITLE
Use of .sh files shunned globally.

### ISSUE THREAD

**Issue by thebetterjort** [strapi/strapi-docker#15]
Don't use .sh files for entrypoint. Shunned. 

Use golang for statically typed and universal support.

**Comment by msgeissler** [comment]
Using node.js itself for the entrypoint should also be possible and may be the better solution.

I don't know golang but is that universal? Or how is it more universal?
The go-package is also quite huge and would blow up the image size if that should be required.

**Comment by lucaperret** [comment]
Strapi is running on Node.js, the alpine image is the lightest possible.
