### ISSUE TITLE
Unnecessary "releases"

### ISSUE THREAD

**Issue by cadavre** [strapi/strapi-docker#152]
I noticed that you make Github releases on both – `strapi/strapi` and `strapi/strapi-docker` repositories. This way you have >1 place to update the versions and it ends up with `strapi/strapi-docker` **not being updated**.

I guess we don't need releases in `strapi/strapi-docker` Github repo, because we have in on Docker Hub and in `strapi/strapi`.

Less work for you guys and less confusion for us when you forgot to update.

**Comment by alexandrebodin** [comment]
Hi @cadavre, We have dropped making releases on this repo for quite a while.

As you are saying, you can just look at the docker hub tags to know what versions are availabel ;)

**Comment by cadavre** [comment]
IMHO please remove existing Github releases to avoid confusion. :)

**Comment by alexandrebodin** [comment]
@cadavre I will create a new and last release with the right links to avoid deleting work made by previous contributors ;) Thanks for the suggestion 💯
