### ISSUE TITLE
Installing graphql throw error

### ISSUE THREAD

**Issue by cesarve77** [strapi/strapi-docker#156]
**Describe the bug**
Installing grapql plugin, I get "A error has occurred" (or something similar) in the admin section

**Steps to reproduce the behavior**
1. Go to Pluging
2. Click on GraphQl
3. wait 

**Expected behavior**
Success message.
In Marketplace - Plugins, GraphQL pluginf appears as no installed but after refresh it change to installed. Maybe the process it taking too much (I have a fast computer)

**Code snippets**

```
strapi    | [2019-11-27T21:44:11.433Z] info Installing graphql...
strapi    | [2019-11-27T21:46:24.383Z] info File changed: /srv/app/yarn.lock
strapi    | [2019-11-27T21:46:24.425Z] info File changed: /srv/app/package.json
strapi    | [2019-11-27T21:46:24.758Z] debug POST /admin/plugins/install (133358 ms) 200
strapi    | [2019-11-27T21:46:24.757Z] info The server is restarting
strapi    | 
mysql     | mbind: Operation not permitted
strapi    | 
strapi    |  Project information
strapi    | 
strapi    | ┌────────────────────┬──────────────────────────────────────────────────┐
strapi    | │ Time               │ Wed Nov 27 2019 21:46:40 GMT+0000 (Coordinated … │
strapi    | │ Launched in        │ 12536 ms                                         │
strapi    | │ Environment        │ development                                      │
strapi    | │ Process PID        │ 8119                                             │
strapi    | │ Version            │ 3.0.0-beta.17.6 (node v12.13.0)                  │
strapi    | └────────────────────┴──────────────────────────────────────────────────┘
strapi    | 
strapi    |  Actions available
strapi    | 
strapi    | Welcome back!
strapi    | To manage your project 🚀, go to the administration panel at:
strapi    | http://localhost:1337/admin
strapi    | 
strapi    | To access the server ⚡️, go to:
strapi    | http://localhost:1337
strapi    | 
```
**System**
Docker https://github.com/strapi/strapi-docker/blob/master/examples/mysql/docker-compose.yml

- Database: MYSQL

**Additional context**
![image](https://user-images.githubusercontent.com/3970983/69761738-fe362180-11b3-11ea-8e79-d83c6e40d81e.png)

**Comment by alexandrebodin** [comment]
@cesarve77 It seems you cannot use the install interface with a docker image. You can still run strapi install graphql by attaching to your image your just by running `yarn add strapi-plugin-graphql` in your project before starting it ;)

**Comment by jdelafon** [comment]
If you `yarn add strapi-plugin-graphql` before starting it, you compile C sources on your host machine for the Linux container target, which often does not end well:
```
strapi_1  | [2020-06-18T06:15:57.480Z] error Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
```

**Comment by sayoojt** [comment]
Create a /Dockerfile and refer the docker file inside docker-compose and we can mention the yarn install or npm install for installing packages with image.

**.Dockerfile** contents below
FROM strapi/base

WORKDIR /app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]

**docker-compose** contents below
version: '3'
services:
  cms:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: your_container_name
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SRV: ${DATABASE_SRV}
      DATABASE_SSL: ${DATABASE_SSL}
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
