### ISSUE TITLE
Admin panel is not working

### ISSUE THREAD

**Issue by QuentinPi** [strapi/strapi-docker#158]
Hi,
I have a problem when I use this docker, I can't access to the admin panel.
It's always redirected to the welcome page. I think it's because the admin panel is not built.

**Comment by alexandrebodin** [comment]
@QuentinPi can you share the steps to reproduce this ? I cannot seem to reproduce using the basic example in the README

**Comment by QuentinPi** [comment]
I use this docker-compose.yml file https://github.com/strapi/strapi-docker/blob/master/examples/prod/docker-compose.yml and I run docker-compose up -d

If I run strapi build, admin panel works.

**Comment by alexandrebodin** [comment]
As you are mounting a volume the image just runs your project as is. If it isn't built it is not going to build it :) 

I'm closing this as you can automate it if you would like on your own.
