### ISSUE TITLE
Error connecting to Mongo with production environment

### ISSUE THREAD

**Issue by LasaleFamine** [strapi/strapi-docker#16]
I'm trying to start the Strapi container passing the `NODE_ENV` var to `production` but after everything is created I have got this error and the container continues to restart:

```sh
I NETWORK  [conn14] Error receiving request from client: SSLHandshakeFailed: SSLHandshakeFailed. Ending connection from ...
```

Is there something I'm missing? Everything working normal with `NODE_ENV=development`.

**Comment by msgeissler** [comment]
This is just a wild guess, but are you using self-signed certificates by chance?
Maybe some middleware (e.g. mongoose) handles certificates differently in development mode.

**Comment by LasaleFamine** [comment]
Hi @msgeissler, thank you for your response. 
Nope, I have simply launched the `docker-compose` with `NODE_ENV=production` trying to simulate a production situation. I have CloudFlare pointing to my machine'IP, so the certificate is served by them, but I think the problem is likely more "internal".

Another thing I noticed is that I was able, just one time, to switch the previously started container in developed mode to production mode and managed it to work, but after a simple restart the error came up again.

**Comment by lucaperret** [comment]
Hi @LasaleFamine, have you try to run it outside the docker environment ?

**Comment by LasaleFamine** [comment]
Actually I had not the time to test outside Docker. Anyway I can confirm I have the problem also without the use of docker-compose. Launching two separate containers for Strapi and Mongo gave the same problem.

**Comment by lucaperret** [comment]
@Aurelsicoko : is there a specific behavior on the database connection when you set `NODE_ENV=production` ?
This bug is more related to Strapi.

**Comment by Aurelsicoko** [comment]
No, but it will use the configurations available in the `./config/environment/production/*.json` files.

**Comment by lucaperret** [comment]
Hi @LasaleFamine could you verify your production configuration ? are you using also SSL authentication for mongodb ?

**Comment by LasaleFamine** [comment]
I'm getting the error just setting `NODE_ENV=production`, so I suppose I'm using the bundled production Strapi configuration.

**Comment by lucaperret** [comment]
Unfortunately, the actual Strapi release used for this docker image (3.0.0-alpha.12) doesn't have the ability to connect to mongodb within SSL.
We'll do our best to build the image with the version `3.0.0-alpha.12.2` asap.

**Comment by lucaperret** [comment]
Hi @LasaleFamine , could you retry with the last docker image released ?

**Comment by LasaleFamine** [comment]
Awesome! Thank you so much for your constant updates @lucaperret.

The issue seems solved now with a fresh clone and `docker-compose up` with `NODE_ENV=production` specified for the Strapi container.

Close whenever you want guys, for me it's working. 👍

**Comment by stephane-r** [comment]
Hey, hello guys !

I've same problem with Strapi and Docker for environment production variable. Can't connect to mongodb :/

**Comment by lucaperret** [comment]
Hi @stephane-r, could you explain here how did you resolve it yesterday ?
