### ISSUE TITLE
How to set database schema in docker-compose.yaml

### ISSUE THREAD

**Issue by robnewton** [strapi/strapi-docker#161]
I want to install Strapi into a different schema than public. I tried setting DATABASE_SCHEMA in the docker-compose.yaml but it didn't have an effect. Is there a way to override this?

EDIT: Using an existing Postgres database and want to segregate the Strapi tables.

**Comment by alexandrebodin** [comment]
Hi @robnewton,

the schema bust be specified in your strapi database.json settings too.

You will have to create a custom image to either copy a predefined database.json file into your project your something.

**Comment by robnewton** [comment]
Ok. I am just changing the docker-compose to use a different database instead however after deleting the volumes and removing the images strapi is still starting up and recreating it's tables in the first database I provide in the docker-compose.yaml. Is there something I need to do to completely clear it out to use a different database?

To try and make sure I have a fresh slate I am doing the following:

`docker-compose rm -s -v strapi
docker rmi strapi/strapi
docker system prune -a
docker volume prune`

I then delete all the tables strapi creates on boot and use docker-compose up -d to bring it all back up. I see it create the tables in the old database I had previously set in the docker-compose.yaml.

**Comment by robnewton** [comment]
Got it working. Actually needed to delete the `/app` directory used as the volume in the docker-compose.yaml:

`volumes:
      - ./app:/srv/app`

Deleted it with `sudo rm app -f -r`
