### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rnkhouse** [strapi/strapi-docker#163]
I am getting below error while installing latest image `strapi/strapi:latest`

    Using strapi 3.0.0-beta.18.2
    No project found at /srv/app. Creating a new strapi project
    Creating a new Strapi application at /srv/app.

    Creating a project from the database CLI arguments.
    Creating files.
    - Installing dependencies:
    Error while installing dependencies:
    warning strapi > boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
    warning strapi > boom > hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
    warning strapi > strapi-utils > knex > @babel/polyfill > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    warning strapi-admin > react-intl > intl-relativeformat@2.2.0: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
    warning strapi-admin > react-virtualized > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    warning strapi-admin > react-datetime > create-react-class > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
    warning strapi-plugin-users-permissions > purest > request > hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
    warning strapi-plugin-users-permissions > purest > request > hawk > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
    warning strapi-plugin-users-permissions > purest > request > hawk > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
    warning strapi-plugin-users-permissions > purest > request > hawk > boom > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
    warning strapi-plugin-users-permissions > purest > request > node-uuid@1.4.8: Use uuid module instead
    warning strapi-plugin-users-permissions > purest > request > hawk > cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
    warning strapi-plugin-users-permissions > purest > request > hawk > cryptiles > boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
    warning strapi-plugin-users-permissions > purest > request > hawk > sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
    warning strapi-plugin-users-permissions > purest > request > hawk > sntp > hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
    warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
    warning strapi-plugin-email > strapi-provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained

    Keep trying!

    Oh, it seems that you encountered errors while installing dependencies in your project.
    Don't give up, your project was created correctly.

**Comment by alexandrebodin** [comment]
Hi @rnkhouse,

Can you plz provide your OS, and the command you ran ?

**Comment by rnkhouse** [comment]
@alexandrebodin I am running on AKS. It's a Kubernetes deployment.

    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: SERVICE_NAME
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: SERVICE_NAME
      template:
        metadata:
          labels:
            app: SERVICE_NAME
        spec:
          terminationGracePeriodSeconds: 30
          containers:
          - name: SERVICE_NAME
            image: IMAGE_NAME
            imagePullPolicy: "IfNotPresent"
            ports:
            - containerPort: SERVICE_PORT
            resources:
              requests:
                memory: "200Mi"
                cpu: "200m"
              limits:
                memory: "200Mi"
                cpu: "200m"
            env:
            - name: DATABASE_CLIENT
              value: "mysql"
            - name: DATABASE_HOST
              value: "DATABASE_HOST_VALUE"
            - name: DATABASE_PORT
              value: "DATABASE_PORT_VALUE"
            - name: DATABASE_NAME
              value: "strapi"
            - name: DATABASE_USERNAME
              value: "DATABASE_USERNAME_VALUE"
            - name: DATABASE_PASSWORD
              value: "DATABASE_PASSWORD_VALUE"
          imagePullSecrets:
          - name: mtesacr

**Comment by alexandrebodin** [comment]
@rnkhouse is this sth that you can reproduice everytime ?

**Comment by rnkhouse** [comment]
@alexandrebodin It worked when I increased the momory and cpu limits of the container.
