### ISSUE TITLE
Creating a custom Dockerfile

### ISSUE THREAD

**Issue by rnkhouse** [strapi/strapi-docker#165]
I think it's better to use custom Dockerfile. But, the instructions are not clear and getting permission error in the execution of `docker-entrypoint.sh`. Also, there are no `node_modules` and `strapi` files in the container. Not sure if this is the right way to implement this:
I am using external `mysql` client for database.

Error:

>starting container process caused "exec: \"/usr/local/bin/docker-entrypoint.sh\": permission denied": unknown

**Dockerfile**

    FROM strapi/base:10

    RUN yarn global add strapi@3.0.0-beta.18.2
    WORKDIR /srv/app
    EXPOSE 1337

    ENV DATABASE_NAME=strapi
    ENV DATABASE_CLIENT=mysql
    ENV DATABASE_HOST=$DATABASE_HOST
    ENV DATABASE_PORT=$DATABASE_PORT
    ENV DATABASE_USERNAME=$DATABASE_USERNAME
    ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
    
    COPY docker-entrypoint.sh /usr/local/bin/
    ENTRYPOINT ["docker-entrypoint.sh"]
    CMD ["strapi", "develop"]

If I run below Dockerfile. I am getting `yarn build` not found error.

**Dockerfile - From custom example file**

    FROM strapi/base
    WORKDIR /srv/app
    COPY ./package.json ./
    COPY ./yarn.lock ./
    RUN yarn install
    COPY . .
    RUN yarn build
    EXPOSE 1337
    ENV NODE_ENV production
    CMD ["yarn", "start"]

What is the best way to create my own `strapi` image?

**Comment by alexandrebodin** [comment]
Hey, 
Have you tried making the COPY to  `/srv/app` instead of `./` ?

**Comment by rrubio** [comment]
I had a similar issue and swapped "yarn" for "npm" see below:

`FROM strapi/base

WORKDIR /myApp

COPY ./package.json ./
COPY ./package-lock.json ./

# RUN yarn install
RUN npm install

COPY . /myApp

RUN npm build

EXPOSE 1337

ENV NODE_ENV production

CMD ["npm", "start"]

**Comment by rnkhouse** [comment]
@rrubio I tried the way you mentioned and getting this error:

    > strapi@0.1.0 start /srv/app
    > strapi start
    
    [2019-12-27T23:05:20.297Z] debug ⛔️ Server wasn't able to start properly.
    [2019-12-27T23:05:20.298Z] error Error: Missing config folder. Please create one in your app root directory
    at module.exports (/srv/app/node_modules/strapi/lib/core/load-config.js:9:11)
    at Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:317:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:196:7)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! strapi@0.1.0 start: `strapi start`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the strapi@0.1.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2019-12-27T23_05_20_309Z-debug.log

**Comment by alexandrebodin** [comment]
Hello @rnkhouse,

You are running the image but do you already have a project in your host folder ?

**Comment by virgil9306** [comment]
Hi @alexandrebodin 

+1 for OP's issue, I have the same problem.

I have:

* This repo in my host folder (I guess that is my "project"?)
* Same `dockerfile` as OP

and got the same issue.

So I did this:

1. Changed to use `npm` like @rrubio 
2. Ran `npm install` to create the package-lock.json

Then I got `npm ERR! missing script: start` (of course, because I do not have the start script that @rrubio used -- do you mind sharing?)

...By the way in my `docker-compose.yml` I am using:

```
volumes:
      - ./app:/srv/app
```

and `WORKDIR /app` in my `Dockerfile`.

**Comment by alexandrebodin** [comment]
I'm not having any issues witth buildign custom images on my side. 

I'm going to close this issue as it is not an issue specific to strapi but to docker usage.

Feel free to comment if you think it should stay open :)
