### ISSUE TITLE
strapi is looking for production.html

### ISSUE THREAD

**Issue by nelajc** [strapi/strapi-docker#172]
on my Dockerfile: NODE_ENV=production npm run --prefix /usr/src/api/strapi-app build

error displayed:
> strapi-app@0.1.0 start /usr/src/api/strapi-app
> strapi start

> [2020-01-21T10:34:10.984Z] error Error: ENOENT: no such file or directory, open '/usr/src/api/strapi-app/public/production.html'

using node 12.x
OS: ubuntu 18.04

**Comment by alexandrebodin** [comment]
Hi @nelajc I think this happened just after migrating. Make sure to read https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#adding-new-root-page-files

Closing this PR for now :)
