### ISSUE TITLE
Docker Compose behind a reverse proxy redirects to wrong domain.

### ISSUE THREAD

**Issue by githubsaturn** [strapi/strapi-docker#173]
Not sure if this is an issue with strapi or strapi-docker. But anyways, here is the gist of the issue:

When you setup the strapi docker through a docker compose, for example the [MongoDB one](https://github.com/strapi/strapi-docker/tree/master/examples/mongo), the installation goes well, and you can view the first page fine. However, if your container is behind a reverse proxy, for example if you're accessing it through `mystrapi,mydomain.com`, the moment you click on the green button to create admin account, it redirects to to `http://localhost:1337/admin` (reported here: https://github.com/caprover/one-click-apps/issues/121)

How to fix:
The redirection shouldn't include the domain, the link should only contain the path, for example:
```
< a href="/admin" >  GO TO ADMIN </a>
```

It should NOT use:
```
< a href="http://localhost:1337/admin" >  GO TO ADMIN </a>
```

Solution:
Either allow the domain to be passed to the container through an environmental variable, or better than that, avoid including the domain in the links and just include the path.

PS:
Actual content:
![image](https://user-images.githubusercontent.com/10582082/73044233-b1c73500-3e36-11ea-9973-546dba943601.png)

**Comment by alexandrebodin** [comment]
Hi @githubsaturn,

You can use the server host and proxy options to achieve that :)

Check the doc https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#server

**Comment by githubsaturn** [comment]
Thanks @alexandrebodin 

This definitely solves the problem, but to align more with de facto standard  way of docker image configs through env vars, is there a way for users to set the same variable through env vars instead of config file?

**Comment by alexandrebodin** [comment]
Using env vars is possible but you will still need to change your configuration file to load the variable from env and then use env var with your image.

Check this to earn more https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#dynamic-configurations

**Comment by derrickmehaffy** [comment]
As @alexandrebodin mentioned you can take the following example: https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#example-3

And configure it with dynamic env variables:

``` json
{
  "host": "localhost",
  "port": 1337,
  "proxy": {
    "enabled": true,
    "ssl": true,
    "host": "${process.env.PROXY_HOST}",
    "port": "${process.env.PROXY_PORT}"
  },
  "cron": {
    "enabled": true
  }
}
```

You may have to play with the boolean values as environment variables don't really support booleans (they are strings).

**Comment by alexandrebodin** [comment]
Closing this Issue with correct answer provided. Feel free to let us know if you still are having issue ;)
