### ISSUE TITLE
SSL connection is required. Please specify SSL options and retry

### ISSUE THREAD

**Issue by rnkhouse** [strapi/strapi-docker#174]
How can I define SSL certificate in the docker file?

I already set `DATABASE_SSL=true` but still I need to provide `ca certificate` somewhere.

**Comment by derrickmehaffy** [comment]
Can you clarify which database you are using, as it largely depends on which ORM is being used.

**Comment by rnkhouse** [comment]
@derrickmehaffy MySQL

**Comment by alexandrebodin** [comment]
Closing this issue as it isn't an issue with the image but a question on usage. Feel free to go on our slack to ask for help ;)

**Comment by CodingWithTashi** [comment]
If you have a configuration somewhere in strapi make sure to disable
`database.js`   update with ` ssl: { rejectUnauthorized: false }`
```
module.exports = ({ env }) => ({
  connection: {
    client: "postgres",
    connection: {
      host: env("DATABASE_HOST", "postgres"),
      port: env.int("DATABASE_PORT", 5432),
      database: env("DATABASE_NAME", "postgres"),
      user: env("DATABASE_USERNAME", "postgres"),
      password: env("DATABASE_PASSWORD", "postgrespassword"),
      ssl: { rejectUnauthorized: false },
    },
  },
});
```

https://github.com/strapi/strapi/issues/5696#issuecomment-608179879
