### ISSUE TITLE
Error of "docker-compose up" for mongo yml

### ISSUE THREAD

**Issue by yxwu** [strapi/strapi-docker#175]
Hi there,
I have the following error when running "docker-compose up" with the mongo yml:
```
strapi    | ⚡️ Start application:
strapi    | $ strapi start
strapi    | [2020-01-31T06:33:00.509Z] debug ⛔️ Server wasn't able to start properly.
strapi    | [2020-01-31T06:33:00.510Z] error Invalid empty username provided
```
So anything wrong?

Thanks
Ray

**Comment by alexandrebodin** [comment]
@yxwu Without seeing your configuration I cant help you. Can you share it ?

**Comment by yxwu** [comment]
@alexandrebodin  

I didn't use any other configuration file, just this one:
`https://github.com/strapi/strapi-docker/blob/master/examples/mongo/docker-compose.yml`

Then run `docker-compose up`

By the way, if I use `https://github.com/strapi/strapi-docker/blob/master/examples/mysql/docker-compose.yml`, then everything is fine.

**Comment by yxwu** [comment]
Sorry, it turns out that I have an old version of strapi/strapi in my system. After specifying `strapi/strapi:3.0.0-beta.18.7-node12-alpine`, mongo yml works fine.
