### ISSUE TITLE
How to deploy/sync changes made in local dev to production?

### ISSUE THREAD

**Issue by kubal5003** [strapi/strapi-docker#176]
I tried to ask this question before here: https://github.com/strapi/strapi-docker/issues/143
It was unfortunately closed with the release of strapi Docker base image.

Having a new production base image is definitely a step in the right direction, however does not fully address the issue of incremental production deployment.

In a real life scenario there's often the case that a new data type is required. New docker image makes it easy to deploy code changes from dev environment to production, but for the new data type to actually work also changes to the database are required. **How does strapi address that need to push schema changes from one database to another?** (conceptually - regardless of the underlying db)

**Comment by lauriejim** [comment]
Hello!
When you develop your app in local (development) your Content Type updates apply some database structure updates on the fly (applied when the server restart)
So when you will deploy your app in production, these updates will be applied to your production database.
After that is you are talking about data (and not data structure) here is the [Feature Request](https://portal.productboard.com/strapi/1-public-roadmap/c/12-migrate-across-environments) in the Public Roadmap.
Feel free to add your need there.

**Comment by kubal5003** [comment]
I was trying this around August and it didn't work for me. Is there any special voo doo magic that I need to perform? I.e. run some script to make it happen? 

AFAIR When I run a new codebase against the old database - the datatype was not visible until I manually transferred schema changes. I was running Strapi against MongoDb.

**Comment by alexandrebodin** [comment]
@kubal5003 When you run strapi the database is autmatically updated whithout having any operation to do. You may have some issue due to your configurations. If you don't mind sharing them we might be able to help you :)

**Comment by alexandrebodin** [comment]
Closing this issue as it isn't an issue with the image but a question on usage. Feel free to go on our slack to ask for help ;)
