### ISSUE TITLE
 This command can only be used inside a Strapi project.

### ISSUE THREAD

**Issue by samarhaider** [strapi/strapi-docker#18]
I am running following command and getting above error.

`docker-compose exec api strapi generate:api product`

**Comment by msgeissler** [comment]
The WORKDIR is defined as `/usr/src/api` in the Dockerfile, that means any command should be executed inside of that directory. What the default `strapi.sh` command does, is create a new project with the name as defined in the environment variables or _strapi-app_ by default if it does not yet exist, **change directory** to the project folder and start the project.

What you should be missing is the part where you change the directory into your actual project. You will have to add that to your command (you will most likely have to wrap the two commands in one bash command or something like that) or, what seems to be the easier method in your case, change the working dir for the exec command (see -w https://docs.docker.com/compose/reference/exec/) to `/usr/src/api/<YOU_PROJECT_NAME>`.

**Comment by lucaperret** [comment]
Hi @samarhaider, good idea. We'll need to improve the entrypoint to handle other arguments.

**Comment by cupofnestor** [comment]
`strapi start` could be removed from `./strapi.sh` then this script could be run as a `CMD` to setup the environment before changing the working directory for the strapi start command and subsequent ones passed by exec,run, etc. This script changes the CWD in bash land, which I think is the main issue here.

Strapi could be run via `ENTRYPOINT`, with default args provided by a CMD.

```Dockerfile
CMD ["./strapi.sh"]
WORKDIR[''$RELATIVE_PATH"]
ENTRYPOINT["strapi"]
CMD["start"]
```

This has the added benefit of using the base `strapi` command as an entrypoint for one-off containers:
```bash
$ docker run -rm strapi/strapi generate api foo
```

**Comment by lauriejim** [comment]
Can you give us an update please.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
