### ISSUE TITLE
Everytime I deploy strapi, it forgets the plugin info

### ISSUE THREAD

**Issue by maxh213** [strapi/strapi-docker#182]
Every time I deploy strapi it forgets the plugin data.

I have an installation of strapi in a git repo and then use a dockerfile to build and deploy it. I can make changes to the data types using yarn develop on my local and then commit and deploy them and it saves it fine. 

However, any changes to plugins like "roles & permissions" and the layout of content for the "content type builder" gets forgotten. This means every deployment all my endpoints lose their authentication and return a 403 which is less than ideal haha. I think I must be missing something.

Thanks very much for any help! Let me know if you need any more detail.

**Comment by alexandrebodin** [comment]
Hi @maxh213 What database are you using ? When deploying strapi if you want to use your local configuration in production you will need to create a migration script. This isn't yet provided by strapi.

**Comment by maxh213** [comment]
ah I see thanks! I'm using postgres. Do you know where the local configuration is stored?

**Comment by maxh213** [comment]
Local and production have seperate databases, it's ok that they have different data on them. But when production gets deployed and it goes offline and the docker image is rebuilt, when it comes back up it has forgotten the details about the plugin. It still has all the info saved in the database. 

I assume this means the plugin info is stored locally?

**Comment by alexandrebodin** [comment]
The plugin configuration are stored in DB but if you change them lcoally they won't be saved in your production DB. This is when you need to create migration script to do that :)

I think you got the hang of it. I'm going to close the issue as it is not related to the dockder image. Feel free to go on our community slack to ask for help on building your migration scripts of course !

**Comment by maxh213** [comment]
Thanks for your help Alex!
