### ISSUE TITLE
Unable to start the server after using duplicate attribute name "ID"

### ISSUE THREAD

**Issue by bazter** [strapi/strapi-docker#183]
Hello, I just started to play with Strapi and after few clicks I broke it and can't start the server anymore.

Repro:

I've used the default command to run the image: 
```docker run -it -p 1337:1337 -v `pwd`/project-name:/srv/app strapi/strapi```

I created first admin account and entered the cockpit.

Then I created my first custom type, added two attributes _Name_ and _ID_ and saved.

Server wasn't able to restart with following error in console:

```
[2020-02-21T11:43:43.192Z] error Impossible to register the 'zeme' model.
[2020-02-21T11:43:43.193Z] error Error: SQLITE_ERROR: duplicate column name: ID
```

If there are any forbidden attribute names, it should be prohibited to enter them imo. Also when there's such error, some kind of rollback would be nice to revert the changes and make strapi work again. Now, how do I remove the type properly so I can start the server again?

Thank you,
Baz

**Comment by alexandrebodin** [comment]
Hi. This issue already exists in the main repository. This one is only about the docker images. 

I'm closing this issue here
