### ISSUE TITLE
How to update to latest version?

### ISSUE THREAD

**Issue by gottlike** [strapi/strapi-docker#184]
I would expect `docker-compose pull && docker-compose up` to update to the newest version. But even though the image is apparently updated, the Strapi code is still fixed to the previous version I was using (it says so on start and in the admin UI). How am I supposed to update?

**Comment by gottlike** [comment]
After a lot of searching, I found the migration guides: https://strapi.io/documentation/3.0.0-beta.x/migration-guide/

I know Strapi is still in beta, so this is not a critical issue.. but you absolutely must provide a standard way of updating (see comment above), before it can be called "stable" - in my opinion. Is that somewhere on the internal roadmap?

**Comment by alexandrebodin** [comment]
Hi,

We will eventually provide some upgrade scripts when we have enough people in the team. 

Upgrading your strapi project isn't realted to the docker images. I'm closing this PR.

**Comment by yxwu** [comment]
Hi there,
Since docker-entrypoint.sh won't run `strapi new ...` again once package.json is available, how can we apply the new strapi upgrade? 
So I assume docker image may need some changes once strapi upgrades.
Your opinion?
Best

**Comment by needleshaped** [comment]
Official documentation wasn't clear for the first time for me either.
Below is a spin-off step-by-step guide from 3.0.5 to 3.1.5 in docker-compose context.

It tries to follow official documentation as close as possible, but includes a some extra (mandatory in my case) steps.

> ## Upgrade Strapi
> 
> - **Important!** Strapi builds itself during first startup, if detects empty folder. See
> https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh
> - **Upgrading Docker image versions DOES NOT upgrade Strapi version.**
> - Follow general and version-specific guide in tandem
> 
> Example of upgrading from 3.0.5 to 3.1.5:

```sh
# https://strapi.io/documentation/v3.x/guides/update-version.html

# Make sure your server is not running until the end of the migration
## That is unclear instruction. Stopped Nginx to prevent access to application, without stopping Strapi itself. 
docker-compose exec strapi bash # enter running container
## Alternative way would be `docker-compose stop strapi` and manually reconstruct container options using `docker`, overriding entrypoint with `--entrypoint /bin/bash`

# Few checks
yarn strapi version # current version installed
yarn info strapi #npm info strapi@3.1.x version # available versions
yarn --version #npm --version
yarn list #npm list
cat package.json

# Upgrade your dependencies
sed -i 's|"3.0.5"|"3.1.5"|g' package.json && cat package.json
yarn install #npm install
yarn strapi version

  # Breaking changes? See version-specific migration guide!

  ## https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html
    ## Define the admin JWT Token
    ## Update username constraint for administrators
    docker-compose exec db bash
    psql strapi strapi
      -- show tables and describe one
      \dt
      \d strapi_administrator
    ## Migrate your custom admin panel plugins

# Rebuild your administration panel
rm -rf node_modules # workaround for "Error: Module not found: Error: Can't resolve"
yarn build --clean #npm run build -- --clean

  # Extensions?

# Start your application
yarn develop #npm run develop
# Confirm & test, visit URL

  # Errors?

  ## Error: ENOSPC: System limit for number of file watchers reached, ...
  # Can be solved by modifying kernel parameter at docker HOST system
  sudo vi /etc/sysctl.conf # fs.inotify.max_user_watches=524288
  sudo sysctl -p

# Modify docker-compose to reflect version changed and avoid confusion !
docker ps
vi docker-compose.yml # e.g. 3.0.5 > 3.1.5
docker-compose up --force-recreate --no-deps -d strapi
# ... and remove old docker image, when no longer required.
```

P.S. We may together improve documentation via https://github.com/strapi/documentation
