### ISSUE TITLE
Dockerfile example

### ISSUE THREAD

**Issue by ppatmigra** [strapi/strapi-docker#187]
It would be nice if the link to the Dockerfile example worked.

**Comment by MattieBelt** [comment]
@ppatmigra which link do you mean?

**Comment by alexandrebodin** [comment]
Hi, Closing this PR as it is missing context and explanation. Feel free to reopen with details :)

**Comment by ppatmigra** [comment]
I am talking about the link to an example Dockerfile.

**Comment by alexandrebodin** [comment]
@ppatmigra Can you please be precise ? what link ? where is it ? Feel free to open a PR to fix the link if you want :)
