### ISSUE TITLE
Strapi-Docker error connecting to Mongo-DB

### ISSUE THREAD

**Issue by jochenthomas** [strapi/strapi-docker#189]
Hi,
I hope you can help me.
I am trying different times now to establish a Strapi Test-Project using a running Mongo-DB.
I can access the MongoDB with the user rights are given in the environment vars (you can see below the existing MongoDB-Users as well as the existing "StrapiDB" on an internal network).

The environment parameters you can see below as well - I thought I should give all the information so you can decide what is important.

But it will not go forward as Strapi is not able to connect to the Mongo-DB, see the following:

```
Using strapi 3.0.0-beta.19.3
No project found at /srv/app. Creating a new strapi project
Creating a new Strapi application at /srv/app.
Creating a project from the database CLI arguments.
Creating files.
Dependencies installed successfully.
Your application was created at /srv/app.

Available commands in your project:
yarn ......

Starting your app...
Building your admin UI with development configuration ...    

✔ Webpack
Compiled successfully in 16.19s
[2020-03-30T10:53:53.091Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-30T10:53:53.092Z] error Error connecting to the Mongo database. 
                           Server selection timed out after 30000 ms 
```

**What I am doing wrong???**
Maybe it's a small issue..., but as I am trying already different times without success, I am a little bit down now ;-)

Thanks in advance for any advise, below all relevant docker information:

<img width="219" alt="Create_Container_basics" src="https://user-images.githubusercontent.com/12627762/77906182-d18c3680-7287-11ea-97e7-4485edbdfbe4.png">
<img width="704" alt="Create_Container_Envir-Vars" src="https://user-images.githubusercontent.com/12627762/77906217-dc46cb80-7287-11ea-9c6b-31763760614c.png">
<img width="468" alt="Create_Container_Network" src="https://user-images.githubusercontent.com/12627762/77906249-ec5eab00-7287-11ea-8e97-c4d6fb6755b9.png">
<img width="588" alt="Create_Container_sharedfolders" src="https://user-images.githubusercontent.com/12627762/77906267-f54f7c80-7287-11ea-8d60-7a3b154101d5.png">
<img width="402" alt="MongoDB_users" src="https://user-images.githubusercontent.com/12627762/77906278-faacc700-7287-11ea-96d1-44019b15eea3.png">
<img width="401" alt="MongoDB_users-rights" src="https://user-images.githubusercontent.com/12627762/77906289-fe404e00-7287-11ea-99cf-e5ae65a47773.png">
<img width="412" alt="database-json" src="https://user-images.githubusercontent.com/12627762/77906298-01d3d500-7288-11ea-8df0-f4a8fbf86506.png">

**Comment by alexandrebodin** [comment]
Hi @jochenthomas 

Have you tried setting the `authenticationDatabase` option to `admin`?

**Comment by jochenthomas** [comment]
Hi thanks for your answer.
YES, as you can see in the second picture --> last Env_vars --> DATABASE_AUTHENTICATION_DATABASE = admin

Also in options I have set 
```
      "options": {
        "ssl": false,
        "debug": true
```
Where I can find the logfile, maybe there is a more detailed explanation?

**Comment by alexandrebodin** [comment]
What I meant is that you need to add this variable to your database.json file too :)

```json
{
  "connections": {
    "default": {
      //...
      "options": {
         "authenticationDatabase": "admin"
       }
    }
}
```

**Comment by jochenthomas** [comment]
Haha,
yes I just did this, but Strapi shuts down again with the same error-message...

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "mongoose",
      "settings": {
        "client": "mongo",
        "host": "192.168.67.83",
        "port": "27017",
        "database": "StrapiDB",
        "username": "StrapiDB_dbOwner",
        "password": "pass"
      },
      "options": {
        "ssl": false,
        "authenticationDatabase": "admin",
        "debug": true
      }
    }
  }
}
```

**Comment by alexandrebodin** [comment]
I honestly don't see anything special to add to your config. 

If your code should be using the env vars you should check this doc: https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#dynamic-configurations

**Comment by jochenthomas** [comment]
Hi, I have seen this too... 
But I don't see any advantage in using dynamic configs.
Because I changed the database.json **directly**.
So what would be possible steps to solve this issue?

I guess, the first point would be to evaluate the log files:
Where exactly I can find the database log file? 
What is the result of activating "debug: true"?

**Comment by alexandrebodin** [comment]
I wasn't sure you were setting the right params in the file that's why i suggested using the env var to be sure it is the same values. 

`debug` is an option to see the sql queries made with the sql connector. This will be useless with mongo.  

You can try running your code with a DEBUG=* env var to see debug info for all the libs. This might give your more infos. I don't see what the issue could be if all the infromations are right to be honest 🤔

**Comment by alexandrebodin** [comment]
Is it possible that it might be a network thing maybe ?

**Comment by jochenthomas** [comment]
In this case, it would not be possible to connect from another device (Notebook) with MongoDB-Tool (noSQLBooster) ....

**Comment by jochenthomas** [comment]
Hi,
I created the container again and made a mistake by defining the env-vars (DATABASE-USERNAM instead of -NAME), so I got the following error message.

```
✔ Webpack
  Compiled successfully in 16.18s

[2020-03-31T11:50:41.022Z] error An index error happened, it wasn't applied.
        - command createIndexes requires authentication
[2020-03-31T11:50:41.023Z] error An index error happened, it wasn't applied.
       - command createIndexes requires authentication
[2020-03-31T11:50:41.023Z] error An index error happened, it wasn't applied.
        - command createIndexes requires authentication
[2020-03-31T11:50:41.025Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-31T11:50:41.025Z] error MongoError: command find requires authentication
    at Connection.<anonymous> (/srv/app/node_modules/mongodb/lib/core/connection/pool.js:460:61)
    at Connection.emit (events.js:210:5)
    at processMessage (/srv/app/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at Socket.<anonymous> (/srv/app/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```
This shows me, that the DB connection is OK.
So what could be the issue here?

**Comment by alexandrebodin** [comment]
AS I told you there is nothing specific to strapi about debug files. You will need to look at your mongo logs to see if the connection is even going to the mongo instance. 

What version of mongo are you using ??

**Comment by jochenthomas** [comment]
Hi,
unfortunately, reading the guide gives no clear answers to that issue.
Luckily, after useless hours, I found the reason  - but would have expected clarification would come from the project owner.

If you follow the instruction (e.g. editing the database.json) please be aware that the username and password you are defining are NOT only for the requested project-database!!!
The user must have nearly **superuser rights** or more specific read/write rights to **ANY database**.

Only incidentally, I saw the advice related to Atlas DB:
```
    Under User Privileges ensure Read and write to any database is selected. Then click Add User to save.
```

So I am a little bit irritated: An enterprise-grade solution that exposes the whole MongoDB to a single user, even only a single project-database is necessary? 

However I am currently in test-mode, so will go further to check out...

**Comment by alexandrebodin** [comment]
Hi @jochenthomas,  Strapi uses mongoose behinds the scenes and we do not do anything special with it. Strapi do run index creation at startup to match with the schema (e.g unique indexes). This explains the error in your last message. 

As your error was abut connecting to the DB I was only focused on this and not the fact that you fixed the connection and had a new error :) 

Hope this answers why you need more user rights enabled. 

I'm going to close this issue as it wasn't coming from the docker image.
