### ISSUE TITLE
On the custom image example, the project should also build in production mode

### ISSUE THREAD

**Issue by ruisilvestre** [strapi/strapi-docker#193]
I'm using the example Dockerfile under strapi-docker/examples/custom to build a custom image of my app, and it's working ok for now, except I had to reorder setting the **production** env variable so the admin ui build reads the correct config.

The file in the repo currently reads:

```
...
RUN yarn build
EXPOSE 1337
ENV NODE_ENV production
CMD ["yarn", "start"]
```
### Actual Result
When we run `docker build ...` the `yarn build` command will be run against the **development** configuration, and you can get different results when running, eg I had the admin panel available on another path in dev than in prod.

### Expectation
When we run `docker build ...` the yarn build command will be run against the **production** configuration, so there is no mismatch.

### Potential solution
I've moved the env declaration above the build step to make it work as I expected.
```
ENV NODE_ENV production
RUN yarn build
EXPOSE 1337
CMD ["yarn", "start"]
```

Not sure there is a real problem with this but it feels the admin ui build process should honour the configuration also.

**Comment by alexandrebodin** [comment]
We can rorder the comand in the example if this is the issue :) It's really up to you how you want to create your custom image :)

**Comment by ruisilvestre** [comment]
I agree, it's a custom image after all so we can do as we please. I guess it can be framed as if building the admin ui in develop and running the project in production is a 'good practice' for Strapi that you want to promote via that custom image. In my case that setup gave me some issues, but easily fixable.

**Comment by alexandrebodin** [comment]
Going to update the Dockerfile. I like your proposal :).
