### ISSUE TITLE
mysql example only works with mysql 5.7

### ISSUE THREAD

**Issue by holygekko** [strapi/strapi-docker#202]
In the mysql example (examples/mysql/docker-compose.yml) the mysql image referenced is 'mysql' which defaults to latest (v8.0.20 at this moment). 

However this configuration doesn't work with mysql 8, it only works with mysql 5 (I think this has something to do with the mysql npm module not supporting a new form of authentication?).

Please adjust to `image: mysql:5.7`

**Comment by alexandrebodin** [comment]
Hi, @holygekko Thank you for the info. If you feel like opening a PR to help out that would be cool :D 

Will try to update when I get some time ;)

**Comment by alexandrebodin** [comment]
Hello, I have update the example to avoid misleading users. Thanks for your help !
