### ISSUE TITLE
Production documentation

### ISSUE THREAD

**Issue by enricostano** [strapi/strapi-docker#204]
Hi!
Many thanks for the good work!

Is there any documentation (with examples and step by step guide) about how to deploy Strapi in production using docker?

In the official documentation there is no trace of `production` environment and you end up (like me) running `strapi develop` in production...

Also, what's the recommended process to start a Strapi project and then bring it to production?

Any input would be appreciated. Thanks!

**Comment by xaiyeon** [comment]
I tried the documentation for Strapi from here:
https://github.com/strapi/strapi-docker/blob/master/examples/postgresql/docker-compose.yml

I get:
`
| Starting your app...
| [2020-05-10T21:39:34.592Z] debug ⛔️ Server wasn't able to start properly.
| [2020-05-10T21:39:34.594Z] error Error:
| Something went wrong installing the "sharp" module
|
| Cannot find module '../build/Release/sharp.node'
| Require stack:
| - /srv/app/node_modules/sharp/lib/constructor.js
| - /srv/app/node_modules/sharp/lib/index.js
| - /srv/app/node_modules/strapi-plugin-upload/services/image-manipulation.js
| - /srv/app/node_modules/strapi/lib/load/load-files.js
| - /srv/app/node_modules/strapi/lib/load/load-config-files.js
| - /srv/app/node_modules/strapi/lib/core/load-config.js
| - /srv/app/node_modules/strapi/lib/core/load-modules.js
| - /srv/app/node_modules/strapi/lib/Strapi.js
| - /srv/app/node_modules/strapi/lib/index.js
| - /srv/app/node_modules/strapi/lib/commands/start.js
| - /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js
|
| - Run "npm rebuild --verbose sharp" and look for errors
| - Consult the installation documentation at https://sharp.pixelplumbing.com/install
| - Search for this error at https://github.com/lovell/sharp/issues
|
|     at Object.<anonymous> (/srv/app/node_modules/sharp/lib/constructor.js:34:9)
|     at Module._compile (internal/modules/cjs/loader.js:956:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
|     at Module.load (internal/modules/cjs/loader.js:812:32)
|     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
|     at Module.require (internal/modules/cjs/loader.js:849:19)
|     at require (internal/modules/cjs/helpers.js:74:18)
|     at Object.<anonymous> (/srv/app/node_modules/sharp/lib/index.js:3:15)
|     at Module._compile (internal/modules/cjs/loader.js:956:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
`

Then I have a question as well, so I created a strapi project on my local machine, then dumped the database and loaded the data to my production machine, but everytime I run Strapi through my own dockerfile and navigate to roles and permissions menu (Strapi is working fine and the database is populated fine from what I see) I get react error.

`Error: Minified React error #130` and it complains about something about an object being empty in console.

**Comment by alexandrebodin** [comment]
Hi @enricostano Have you looked at the examples folder in this repository ? 

When using the strapi/strapi image the app will by default run in development but it is as simple as changing the command to use strapi start and set a NODE_ENV=production flag. 

You can find an example [here](https://github.com/strapi/strapi-docker/blob/master/examples/prod/docker-compose.yml)


The better way is to create a custom image to match your specific needs: you can find examples [here](https://github.com/strapi/strapi-docker/tree/master/examples/custom)

Closing this issue for now. Let me know if you still think this should stay opened ;)
