### ISSUE TITLE
Cross-platform development

### ISSUE THREAD

**Issue by Brad-Christie** [strapi/strapi-docker#205]
Hey, been using docker to work on a project I dev primarily in Windows (which is fine). "Issue" is around some fuss w/ node_modules and the implications of being cross-platform. Let's see if I can explain:

In windows you create a project (`npx strapi new foo --quickstart`). Voila, it's up and we're off to the races. Shift gears to the [docker-compose](https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose) model (great post, btw) and things become...complicated.

First you start off mounting your volume and ignoring the basics via `.dockerignore`. That's fine, but now the image wants to write back changes, so there's a bit of a clash. (esp given _my_ node modules targets win, _docker's_ will want to target *nix). No bueno.

Next you mount the volume, but also mount `/srv/app/node_modules` (so at least they're not written back and the image still has them). When you do that, the `docker-entrypoint.sh` fouls up because it only performs a [if exists](https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh#L25) check on node_modules, not if exists and populated. Furthermore, the build step [is](https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh#L31) [skipped](https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh#L35) when it's not an install.

I suppose what I'm asking (and if I'm being clear describing the issue) is if there is the potential to make two changes to the entrypoint? One to install so long as node_modules is non-existent **or** empty. The second, when an install is performed (and maybe based on a pre-check of `build` existing) perform a build? As i see it, it shouldn't hurt much of the typical scenarios:

* fresh instance (`docker run -it strapi/strapi`)  
  works as-is, strapi will install, build and run
* base image  (`FROM strapi/strapi ...`)  
  access to tooling remains, nothing too extravagent except maybe a couple additional logical expressions (assuming you didn't alter CMD).
* repeated dev workflow improved (`docker-compose up`)  
  now when you link a local project to the container, it will consistently use its native depdendencies and perform a build if necessary. This is mainly driven off the existance of `- /srv/app/node_modules` definition within your docker-compose's `volumes`.

Thoughts?

**Comment by alexandrebodin** [comment]
Hello, thank you for the ideas. 

If you feel like opening a PR to help us out this would be really helpful as we are still a really small team.

**Comment by fanvyr** [comment]
Encountering this error too. 
Through the volume, my node_modules folder is mounted to the app. 

One Submodule need plattform-specific binaries, and an a mac i have darwin - but the strapi/strapi images needs linux binaries...

Can't believe nobody experienced this?

**Comment by Brad-Christie** [comment]
Just pushed PR #216 to address this. Standard workflow should apply, but also recommend adding following to package.json:

```
  "scripts": {
    "postinstall": "strapi build"
  }
```

**Comment by alexandrebodin** [comment]
Closing as the PR was merged
