### ISSUE TITLE
Base docker image lacks version tags

### ISSUE THREAD

**Issue by RileyMShea** [strapi/strapi-docker#206]
Currently the base images only have node version tags.

Since there are breaking changes introduced between `beta 3.0.0beta20.3` to `3.0.1` stable, it breaks production builds afaik.  

Currently I get an error from the a docker container that has a beta 20.3 structure but got rebuilt with 3.0.0 stable:
```
Error: Cannot find module '/my-path/strapi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

Proposing either:

* Strapi version tags for base images
* or documentation for how to avoid breaking production systems when new base docker images are released.

**Comment by alexandrebodin** [comment]
Hi, the images are all tagged. You can check the tags on dockerhub. 

Closing as this is already in place.

**Comment by RileyMShea** [comment]
@alexandrebodin I  only see tags for node versions on the `strapi/base` images here https://hub.docker.com/r/strapi/base/tags .  I was hoping for tags for the actual strapi version similar to what is currently available on `strapi/strapi` here https://hub.docker.com/r/strapi/strapi/tags
