### ISSUE TITLE
Mongo docker-compose.yml example env variable

### ISSUE THREAD

**Issue by DHvD-R** [strapi/strapi-docker#207]
**Describe**
In the mongo docker-compose.yml example it seems one of the env variables has the wrong name:
`- DATABASE_AUTHENTICATION_DATABASE=strapi`

**Solution**
Should be:
`- AUTHENTICATION_DATABASE=strapi`

**Comment by alexandrebodin** [comment]
Hi, thank your for the info ! I made the change :)
