### ISSUE TITLE
plugin email cog button missing, 3.0.1-node12-alpine image issue ?

### ISSUE THREAD

**Issue by yxwu** [strapi/strapi-docker#208]
![Screen Shot 2020-06-04 at 11 42 55 AM](https://user-images.githubusercontent.com/6853444/83798121-9aa41980-a658-11ea-9926-a2fbba29c995.png)
I use the following command to launch strapi, and found a weird problem, the cog button of the Email plugin is missing, ie. the Email setting page is lost.

$ docker run -it -p 1337:1337 -v `pwd`/strapi-docker:/srv/app strapi/strapi:3.0.1-node12-alpine

**Comment by alexandrebodin** [comment]
Hello @yxwu, This is intended, If you read the migration guide from beta to v3.0.x you will see we moved the email configurations to files. 

https://strapi.io/documentation/v3.x/migration-guide/migration-guide-beta.20-to-3.0.0.html

Closing this issue :)

**Comment by yxwu** [comment]
My bad, thanks!
