### ISSUE TITLE
Unable to delete the record in strapi admin for a model - gives error message

### ISSUE THREAD

**Issue by rmssoftwaretech** [strapi/strapi-docker#21]
Unable to delete the record in strapi admin for a model - gives error message

  | [2018-05-23T01:51:27.387Z] info Your server is running at http://localhost:1337
api_1  | [2018-05-23T01:51:27.387Z] debug Time: Wed May 23 2018 01:51:27 GMT+0000 (UTC)
api_1  | [2018-05-23T01:51:27.387Z] debug Launched in: 2218 ms
api_1  | [2018-05-23T01:51:27.387Z] debug Environment: development
api_1  | [2018-05-23T01:51:27.387Z] debug Process PID: 15
api_1  | [2018-05-23T01:51:27.387Z] debug Version: 3.0.0-alpha.12 (node v9.11.1)
api_1  | [2018-05-23T01:51:27.387Z] info To shut down your server, press <CTRL> + C at any time
api_1  | [2018-05-23T01:51:33.272Z] debug GET /content-manager/explorer/events/count?source=content-manager (35 ms)
api_1  | [2018-05-23T01:51:33.281Z] debug GET /content-manager/explorer/events?limit=10&skip=0&sort=_id&source=content-manager (24 ms)
**api_1  | [2018-05-23T01:51:38.240Z] error this.updateRelations is not a function**
api_1  | [2018-05-23T01:51:38.240Z] debug DELETE /content-manager/explorer/events/5b047065098ddd77ae3c4307?source=content-manager (22 ms)

**Comment by lucaperret** [comment]
Hello @rmssoftwaretech, this bug is more related to [Strapi's core](https://github.com/strapi/strapi).

**Comment by rmssoftwaretech** [comment]
Thanks !
