### ISSUE TITLE
Strapi times out on Mongo

### ISSUE THREAD

**Issue by Slethael** [strapi/strapi-docker#210]
### Describe the bug
While creating a new project with the strapi/strapi image, Strapi can't find Mongo on the local machine when the default Docker Gateway is specified, leaving me with a timeout issue. Below is the exact issue :

```
[2020-06-11T17:14:03.894Z] debug ⛔️ Server wasn't able to start properly.
[2020-06-11T17:14:03.895Z] error Error connecting to the Mongo database. Server selection timed out after 30000 ms
```

#### Steps to reproduce the behaviour

Run the line specified in **Additional Info**

#### Expected behaviour
Strapi should be able to connect to the local Mongo instance without timeout.

### Additional info
```
docker run -it --detach 
-e DATABASE_CLIENT=mongo
-e DATABASE_NAME=strapi
-e DATABASE_HOST=172.17.0.1
-e DATABASE_PORT=my_port
-e DATABASE_USERNAME=strapi-usr
-e DATABASE_PASSWORD=my_secret_pass
-e DATABASE_AUTHENTICATION=strapi
-e VIRTUAL_HOST=my_domain_name.com
-e VIRTUAL_PORT=1337
-e LETSENCRYPT_HOST=my_domain_name.com
-e LETSENCRYPT_EMAIL=postmaster@my_domain_name.com
-p 1337:1337
-v my_path/strapi-test:/srv/app
strapi/strapi
```

is the line used to launch the image. As you can (probably) tell, it is used in conjunction with nginx-proxy and letsencrypt-companion.

#### Tried

- Double and triple-check credentials and env variables
- Going in the strapi container via an interactive shell, installing mongo shell and connecting manually with the exact same credentials passed in the `docker run` command: works perfectly fine
- Adding and removing `DATABASE_AUTHENTICATION` from env args, with no results
- Passing to true the `DATABASE_SSL` env arg, with no results
- As suggested by [this issue](https://github.com/strapi/strapi/issues/4484), passing `--db-auth`as EXTRA_ARGS, with no results

### System

Node.js version: not relevant
NPM version: not relevant
Strapi image version: strapi/strapi:latest
Database: MongoDB v4.0.18
Operating system: Debian 9.12 Stretch

**Comment by rizvankukad** [comment]
I am also facing same issue.

**Comment by vinod77** [comment]
I am facing the same issue. Not able to connect to Mongo DB (either Mongo running inside Docker or on local machine) from App running inside Docker.
Attaching Screenshot:

<img width="1126" alt="Dockerfile — strapi-default-app-20 3 2020-06-12 02-28-26" src="https://user-images.githubusercontent.com/23507845/84477034-9ed1c780-ac54-11ea-90b1-29ec1b691c07.png">

**Comment by Shailu4u** [comment]
I'm facing same issue but with Postgres
[2020-06-11T19:18:31.035Z] debug ⛔️ Server wasn't able to start properly.
[2020-06-11T19:18:31.037Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

**Comment by RaimonxDev** [comment]
> I'm facing same issue but with Postgres
> [2020-06-11T19:18:31.035Z] debug ⛔️ Server wasn't able to start properly.
> [2020-06-11T19:18:31.037Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

Hello, most likely you have problems with the credentials, in postgress if you do not declare the name of the databases (POSTGRESS_DB) it will automatically put the same value of POSTGRES_USER .. so make sure your credentials are correct

**Comment by RaimonxDev** [comment]
Can you show the mongo container to see its sample or test credentials?

**Comment by alexandrebodin** [comment]
Hello, This looks like an help question and not a an issue with the containers. 

The containers are just nodejs containers with just some more dependencies installed to run strapi. They do not do anything specific with database connections.

I'm going to close this question in order to keep the github issues focused on bugs.
You should go to our community slack or stackoverflow to get more help on setting up your specific usecase :)

**Comment by SalahAdDin** [comment]
I have the same problem and I'm just using the default compose file which is provided by `strapi`.
