### ISSUE TITLE
3.0.2 Not Available on Dockerhub

### ISSUE THREAD

**Issue by RileyMShea** [strapi/strapi-docker#212]
# Description
Tags for strapi 3.0.2 show up on https://hub.docker.com/r/strapi/strapi but the actual images don't appear to be present https://hub.docker.com/r/strapi/strapi/tags.

## Followup

> From now on we are only going to release the new images on docker hub without making releases on this github repository.

It seems this repo isn't being updated for releases anymore, is it still the the best place for strapi/docker issues? Or is the main repo a better place?

**Comment by alexandrebodin** [comment]
Nice catch, We built the images but didn't push them. It should be good now :) Closing the issue

The releases aren't made on github directly as the images don't need to be updatde to release the new versions.

**Comment by RileyMShea** [comment]
Sweet, thank you.  Looks like a great update.
