### ISSUE TITLE
Launch yarn build in CMD step for reading env var of container

### ISSUE THREAD

**Issue by sandrotaje** [strapi/strapi-docker#218]
The problem is that you have to know env var during the compilation of Dockerfile but sometimes, if you have for example multiple deployment(test, stage, production) is better to read env file from the server you are deployed.
It's difficult to explain but i post my dockerfile to better explain me.

Dockerfile
```Dockerfile
FROM strapi/base
WORKDIR /srv/app
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . .
ENV NODE_ENV production
EXPOSE 1337

RUN chmod a+x /srv/app/run.sh

CMD ["/srv/app/run.sh"]
```
run.sh
```bash
#!/usr/bin/env bash
yarn build
yarn start
```

With this configuration you can use ENV VAR from, for example, your docker-compose so you are able to change also the URL of your admin not when you build docker file but when you use it.

Because if you run yarn build on dockerfile, in some situation, you don't have contextual information, but if you run on the CMD step you can have this contextual information.

I hope i've been clear enought.

**Comment by alexandrebodin** [comment]
Hi @sandrotaje,

For deployment purposes you should  always create your own DockerFile. 
I'm not sure I understand what you are suggesting ?

**Comment by sandrotaje** [comment]
Yes, it's what i did and what i posted is my Dockerfile.
I suggest to insert in the example directory also this configuration because can be helpfull to who wants to read enviroment variable that modify the strapi frontend build. 
I use this because i wanted to put strapi under a reverse proxy with /api for api and a /dashboard for the admin panel. The problem is that to make this works you have to set amin.url and url on server.js file conf, but strapi needs to know this variable also when you run yarn build and if you put yarn build in the RUN step of Dockerfile is executed in an enviroment where you probably don't have this information(in my case i use gitlab-ci to build the image and push in a docker registry). Instead, if you run the yarn build inside the CMD step is executed in the container and so you can access enviroment variable from there(for example set from a docker-compose file).

I hope i've been more clear.

**Comment by alexandrebodin** [comment]
Thanks, no problem with adding more examples. You can make a PR if you want :)

**Comment by sandrotaje** [comment]
I post also my server.js and my nginx conf
server.js
```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1338),
  url: env('URL', ''),
  admin: {
    url: env('ADMIN_URL', '/admin')
  }
});
```

```conf
# Strapi API
        location /api/ {
                rewrite ^/api/(.*)$ /$1 break;
                proxy_pass http://strapi;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_pass_request_headers on;
        }

        # Strapi Dashboard
        location /dashboard {
                proxy_pass http://strapi/dashboard;
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_pass_request_headers on;
        }
```

**Comment by sandrotaje** [comment]
Ok thank you
