### ISSUE TITLE
Update doesn't work in case of strapi running on docker container

### ISSUE THREAD

**Issue by rmssoftwaretech** [strapi/strapi-docker#22]
Update doesn't work in case of strapi running on docker container.  Doesn't update the record or the image attached.

1  | [2018-05-23T01:53:12.539Z] debug GET /content-manager/explorer/events/5b047065098ddd77ae3c4307?source=content-manager (48 ms)
api_1  | [2018-05-23T01:53:12.547Z] debug GET /content-manager/layout?source=content-manager (25 ms)
api_1  | [2018-05-23T01:53:19.538Z] error this.updateRelations is not a function
api_1  | [2018-05-23T01:53:19.540Z] debug PUT /content-manager/explorer/events/5b047065098ddd77ae3c4307?source=content-manager (42 ms)

**Comment by lucaperret** [comment]
Hello @rmssoftwaretech, do you try to upload files ?

**Comment by rmssoftwaretech** [comment]
Regular update is not working. It displays the original data.

**Comment by rmssoftwaretech** [comment]
Yeah it works fine outside the container. !!

**Comment by rmssoftwaretech** [comment]
It fails with the error in container : error this.updateRelations is not a function

**Comment by lucaperret** [comment]
Could you try to use the `3.0.0-alpha.12` as it's the version used in this docker image.

**Comment by lucaperret** [comment]
Could you retry with the last docker image that includes the v3.0.0-alpha.12.4 ?

**Comment by lucaperret** [comment]
This is more linked to the core Strapi's package.
