### ISSUE TITLE
Admin Page taking longer than 2 minutes to load

### ISSUE THREAD

**Issue by brenojac** [strapi/strapi-docker#222]
![Captura de tela de 2020-06-26 15-11-36](https://user-images.githubusercontent.com/563016/85888330-c467e080-b7bf-11ea-8881-6a16311b8ef0.png)

Helo Strapi team,

I just installed a fully working Strapi stack using Docker compose and it's all fine, except the admin page is taking a long time to load. I searched and found it is a common issue that would be solved in your beta release. But unless I'm wrong, the Strapi version for docker compose is the latest, correct? 

You can check the screenshot above in live mode at https://cms.projetoalex.cc/

If there's anything I can to do to solve this issue, please let me know. 

regards,

- Breno

**Comment by alexandrebodin** [comment]
Hello, It only take 2s for me to load the link you shared. Are you hosting your in another region of worlf ? 
Your app is also running in development mode. Building it for the production mode when deploying will improve performances. 

I'm going to close as it isn't an issue with the docker container itself.
