### ISSUE TITLE
Strapi Docker deployment in kubernetes with no persistent storage

### ISSUE THREAD

**Issue by stanleyyuenyiu** [strapi/strapi-docker#227]
im facing the same issue for many people, 

strapi needed to deploy docker/kubernetes, 

there is no persistent storage at all, 

so when user create a new content type, 

it will generate code for the API, 

but if somehow we restart the docker, everything are gone, 

how do we solve?

**Comment by alexandrebodin** [comment]
Hello, This is not something to change in the strapi images but rather mount some persiste file storage in your images with kubernetes. Depending on the platform you are using (AWS , GCP...) you will need to figure that out on their documentation.

An example here https://strapi.io/blog/deploy-strapi-on-kubernetes-with-https. 

Closing as we don't have any bug to fix on the images

**Comment by stanleyyuenyiu** [comment]
@alexandrebodin thx for the reply

but i expect strapi is a stateless software, turn out it will generate code for the api, and this is quite unusual.

i know i can find some storage to resolve the issue 

but if we are trying to move the strapi from uat -> production, it means i need to download the code from the uat, and then build a new docker to push to production

now do you see the issue?

**Comment by alexandrebodin** [comment]
Sure I get your issue, 

The actual workflow in a strapi project is that you should build your schema before moving to production. 
The generated schemas should exist before the project is moved to production. (commited into versionning for example).

**Comment by stanleyyuenyiu** [comment]
@alexandrebodin oh, then it make more sense, im thinking at that way too

thank you very much
