### ISSUE TITLE
Unable to generate controller or model

### ISSUE THREAD

**Issue by mathb67** [strapi/strapi-docker#23]
Hi
When i try to generate a model or a controller inside my api container, i get this error :
`error No generator called `model` found.`
`error No generator called `controller` found.`

The others generators are working fine.

**Comment by lucaperret** [comment]
Hello @mathb67, this has been fixed here https://github.com/strapi/strapi/pull/1184.
We'll do our best to upgrade the Strapi version in the docker image to `3.0.0-alpha.12.2` asap.

**Comment by mathb67** [comment]
Oh great ! Thanks @lucaperret

**Comment by lucaperret** [comment]
Could you retry with the last docker image that includes the v3.0.0-alpha.12.4 ?

**Comment by mathb67** [comment]
It works like a charm, thank you !
