### ISSUE TITLE
content type builder => 400

### ISSUE THREAD

**Issue by OloZ17** [strapi/strapi-docker#234]
Version: 3.1.3 (node v12.18.2) 
Edition: Community

Just trying => 
https://github.com/strapi/strapi-docker/blob/master/examples/postgresql/docker-compose.yml

Can't create a new collection type and save fields
Msg => an error occurred

Strapi logs =>
[2020-08-01T12:46:41.900Z] debug POST /content-type-builder/content-types (45 ms) 400

it's annoying

**Comment by alexandrebodin** [comment]
Hi, can you check the error in your browser network tab to understand what the error is. Right now I don't have engouh info to help you :)

**Comment by OloZ17** [comment]
My bad => {"error":{"contentType.name":["Content Type name `Agenda` cannot be pluralized. \nSuggestion: add Item after the name (e.g News -> NewsItem)."]}}
