### ISSUE TITLE
DB variables in strapi/base

### ISSUE THREAD

**Issue by bazzou789** [strapi/strapi-docker#235]
Hi!

I want to use strapi/base to build a custom image for CI/CD.

How can I pass DB variables to the image ?

Thx!

**Comment by alexandrebodin** [comment]
Hello, You can pass env vars to any docker containers running using the -e option or using docker-compose. This is a docker question not an issue with the image :)

**Comment by sgauthiertremblay** [comment]
Thx for the reply!

So if I pass the same environment variables like DB_HOST, this strapi image will understand them ?

**Comment by alexandrebodin** [comment]
The `strapi/base` image doesn't do much it is a simple node image with some required dependencies. So you need to configure your database.js config file in your app to allow the env vars and then it will work. 

For the `strapi/strapi` image it will create a simple sqlite project, so if you need more you will need to configre it first before using env vars. 

See it like a normal nodejs project where your first need to set the env vars you want in your code before you can use them with docker:)
