### ISSUE TITLE
@koa/cors/-/cors-3.1.0.tgz Not found 

### ISSUE THREAD

**Issue by tommyboylab** [strapi/strapi-docker#236]
Trying to build a docker image of Strapi leads to the following error:

```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@koa/cors/-/cors-3.1.0.tgz: Request failed \"404 Not Found\"".
```

- Dependency should be updated if no longer existing

Using Strapi/base image

**Comment by tlehwalder** [comment]
Registry issues - yarnpkg/yarn#8279

**Comment by alexandrebodin** [comment]
Hi, indeed we cannot do much about it the npm registry was down at that time. I'm closing this issue here :)
