### ISSUE TITLE
Not reloading when editing source code

### ISSUE THREAD

**Issue by Fl4zher** [strapi/strapi-docker#237]
When i edit the source code, the application is not reloading, as it would without docker.

Eg. If i edit a controller code, the app will not reload. I have to restart the container.

**Comment by alexandrebodin** [comment]
Hello @Fl4zher I will need more information here, What config are you using, how are your running your containers, on what system. Thanks !

**Comment by Fl4zher** [comment]
Hi @alexandrebodin 

I am using docker-compose with Docker Desktop v.2.3.0.4 on Windows 10

My config looks like this: 
`version: "3"
services:
  strapi:
    image: strapi/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "3001:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    networks:
      - strapi-app-network
    volumes:
      - strapidata:/var/lib/postgresql/data
networks:
  strapi-app-network:

volumes:
  strapidata:
`

**Comment by apteles** [comment]
Hi @Fl4zher. I would like know. Are you using WSL in Windows?
I'm question it, because can be problem with permission files. Reported in [PR](https://github.com/strapi/strapi-docker/pull/226)

Another thing to note is if your application is located in folder ./app. See:
https://prnt.sc/tw0hry
One important thing to note too is the logs of your services. ```docker logs <id-container>```. It's very helpful to troubleshooting.
Show us the log of service strapi.

**Comment by Fl4zher** [comment]
Hi @apteles 
I am using WSL yes. 
The permission file is not a problem. The problem is when i edit anything in the source code, the server won't restart as it should. 

Example scenario: 
I want to edit a controller in my Product api. 
When i edit the controller, i expect the server to restart so the changes have been applied to the application. 
But what it does is simply nothing. No reaction at all. 
---- 

I've tried to install a new strapi app and then inside the app folder ran: 
```docker run -it -p 1337:1337 -v `pwd`:/srv/app strapi/strapi```

**Comment by Fl4zher** [comment]
Okay i've found the issue. The project should be located in the WSL, and not in C:. It took me days to figure it out. Should be written somewhere.
