### ISSUE TITLE
lodash issue on docker-compose up

### ISSUE THREAD

**Issue by SharkeyO** [strapi/strapi-docker#24]
I'm having issues with the official docker wrapper for strapi.io --> whenever I run docker-compose up, I am getting errors for lodash to not have been found. When running the docker container for the very first time (clean install), everything is running smoothly, second attempt will return the error below.

```
api_1  | internal/modules/cjs/loader.js:550
api_1  |     throw err;
api_1  |     ^
api_1  | 
api_1  | Error: Cannot find module 'lodash'
api_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
api_1  |     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
api_1  |     at Module.require (internal/modules/cjs/loader.js:598:17)
api_1  |     at require (internal/modules/cjs/helpers.js:11:18)
api_1  |     at Object.<anonymous> (/usr/src/api/strapi-app/admin/controllers/Admin.js:5:11)
api_1  |     at Module._compile (internal/modules/cjs/loader.js:654:30)
api_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
api_1  |     at Module.load (internal/modules/cjs/loader.js:566:32)
api_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
api_1  |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by ashishgkwd** [comment]
I ran into this issue after updating to `alpha.12.2` but was not able to troubleshoot the issue.
As a workaround a fresh install with the following steps fixed it for me:

- Bring down the containers `docker-compose down`
- Deleter the `db` and `strapi-app` folder created on your disk
- Update the `RUN` in DockerFile from `npm install -g strapi@3.0.0-alpha.12` to `npm install -g strapi@3.0.0-alpha.12.2`
- Again run `docker-compose up`

**Comment by ashishgkwd** [comment]
My bad, I just saw there is already a branch available for `alpha.12.2` 😶

**Comment by awerffeli** [comment]
I get the same error. Any fix for this?

**Comment by lucaperret** [comment]
Have you tried with the last Strapi's release ? If it's not working, you could report it to the Strapi's repo.

**Comment by lucaperret** [comment]
Could you retry with the last docker image that includes the v3.0.0-alpha.12.4 ?

**Comment by sriharsha186** [comment]
I am facing the same issue even with the latest version 12.4

**Comment by lucaperret** [comment]
Could you report it to the Strapi's core repo please.

**Comment by mkhennoussi** [comment]
Still not working for me, same error on "docker-compose up" any ideas ? Thanks
