### ISSUE TITLE
Docker image with node v14

### ISSUE THREAD

**Issue by gilmarllen** [strapi/strapi-docker#248]
It would be great if we have a docker image using Node 14, since it has more tools to use in the backend code, like optional-chaining for example.

**Comment by derrickmehaffy** [comment]
@alexandrebodin can we create a docker tag for testing on node v14?

**Comment by alexandrebodin** [comment]
Multiple dependencies of strapi don't support node 14 yet so we can't create a node 14 docker image. As soon as this will be available we will add one

**Comment by gilmarllen** [comment]
OK, no problem. Thanks by the attention!

**Comment by iicdii** [comment]
@alexandrebodin it's time to add one since Node 14 is now LTS and Strapi supports it.
