### ISSUE TITLE
Connection Refused When Using Nginx Proxy

### ISSUE THREAD

**Issue by MehrdadKhnzd** [strapi/strapi-docker#251]
**Describe the bug**
I followed the instruction here:
https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html
But Nginx gives me 502 - Connection Refused.

**Expected behavior**
It should work!

**Code snippets**
It's just like the link above, except I don't have `https`.

**System**
I'm using `strapi/strapi` docker image, the latest one.

**Additional context**
I also tried adding `proxy: true` to the server config, which not worked.

**Comment by alexandrebodin** [comment]
Hello, you need to add the `yarn build` step in your Dockerfile

**Comment by derrickmehaffy** [comment]
> Hello, you need to add the `yarn build` step in your Dockerfile

Something similar to this:
```
FROM node:lts-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build
EXPOSE 1337
CMD ["yarn", "start"]
```

**Comment by MehrdadKhnzd** [comment]
Hey there, sorry for the delay. I found out the problem some days ago but I was very busy I couldn't post it here. The problem was here:
```
upstream strapi {
    server 127.0.0.1:1337;
}
```
As I said, I used Nginx in a container, and by doing that, I was referencing the Nginx container itself when I wrote `127.0.0.1`. I changed it to the container name and now it works! Although I still can't get the admin panel and the documentation from the subpath, which may be another thread or issue, at least the API works itself, and I will open another issue for that if needed.
Thanks again!

**Comment by maggie0002** [comment]
> It would appear the Admin is not being rebuilt then based on: https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh
> 
> That would be an issue to post on https://github.com/strapi/strapi-docker though.

I just experienced this issue too, and lost hours trying to work out what the problem is. The yarn build inside the container fixed it, but I agree, the Admin should be rebuilt when you provide a PUBLIC_URL, or the PUBLIC_URL should be a variable read from a config file.
