### ISSUE TITLE
More guidance regarding https and docker

### ISSUE THREAD

**Issue by raveesh-me** [strapi/strapi-docker#252]
## Use Case
I have a docker-compose based development workflow where we have one strapi instance and one nodejs instance for deploying a nextJS server. Things have been working really well with us using a sqlite based setup for development

Now we want to stage it on production. The architecture is almost like:
1. S3 provider for storage
2. Sendgrid for Email
3. MongoDB from AWS DoccumentDB
4. Strapi and another NodeJS server for nextJS web-app on a T3a.medium EC2 instance

The part where I'm stuck now is if strapi is available at localhost:1337 to the EC2 instance and I link ports 1337 of instance to 1337 of container, 
And 80, 443 of server to 8080 of the nextJS  container

How do I get SSL/HTTPS to work?

Some guidance on this will be really helpful!

**Comment by alexandrebodin** [comment]
Hello, To add ssl you should use a reverse proxy like nginx or caddy :) We do not support adding ssl certificates to the node server as it is not a recommended practice :)

**Comment by raveesh-me** [comment]
Thanks so much for clarifying.
