### ISSUE TITLE
install on windows fails due to mongoerror

### ISSUE THREAD

**Issue by philippfrenzel** [strapi/strapi-docker#26]
MongoError: not authorized on strapi to execute command { listIndexes: "users-permissions_role", cursor: {}, lsid: { id: UUID("ba7326b6-5f66-445e-99fd-96a0b95d9a00") }, $db: "strapi" }

**Comment by lauriejim** [comment]
Hello @philippfrenzel , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

**Comment by philippfrenzel** [comment]
Hi, do you need any additional information? btw. i think I have a working docker compose.yml after hours of testing ... :)

**Comment by philippfrenzel** [comment]
`
version: '3.1'

services:
  api:
#    image: strapi/strapi
    build:
      context: .
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=pass
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      - ./strapi-app/node_modules:/usr/src/api/strapi-app/node_modules
    depends_on:
      - mongo
    restart: always

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    restart: always

volumes:
  mongodata: 

# C:/PFRENZEL/GIT/strapi/strapi-docker/db

`

**Comment by philippfrenzel** [comment]
and you need a .env file within the project root with:

# Development environment settings for docker-compose
# ===================================================
#

# set environment to windows
COMPOSE_CONVERT_WINDOWS_PATHS=1

COMPOSE_PROJECT_NAME=itec

**Comment by KerryRitterWaa** [comment]
Same issue here on Windows 10. Followed the install instructions on strapi.io, ran `strapi start`, and got the same error.

**Comment by lucaperret** [comment]
Hello @philippfrenzel, could you report it to the main `strapi/strapi` repo ?

**Comment by philippfrenzel** [comment]
Hi, I will try to report it - the problem is, that the check for the empty dir is an issue with the config above

**Comment by lucaperret** [comment]
Related to the core Strapi's package
