### ISSUE TITLE
Dashborad still shows older Strapi version after upgrade

### ISSUE THREAD

**Issue by sebqq** [strapi/strapi-docker#260]
So I've just upgraded my strapi application inside of docker container and my console shows right version number:

<img width="902" alt="Screenshot 2020-11-16 at 09 08 34" src="https://user-images.githubusercontent.com/33039909/99227427-80678d80-27eb-11eb-9867-94601f5b7749.png">

But the problem is that admin dashboard still shows older strapi version:

<img width="336" alt="Screenshot 2020-11-16 at 09 08 45" src="https://user-images.githubusercontent.com/33039909/99227442-89f0f580-27eb-11eb-8833-15ff3ba1d467.png">

During update I followed steps from migration guide and used `npm run build -- --clean` command to rebuild admin panel. My Dockerfile looks like:

<img width="315" alt="Screenshot 2020-11-16 at 09 10 51" src="https://user-images.githubusercontent.com/33039909/99227544-ac830e80-27eb-11eb-91b5-cc97caa66922.png">

Also my console during build process displayed following message so I think that --clean build was succesfully completed:

<img width="456" alt="Screenshot 2020-11-16 at 09 12 04" src="https://user-images.githubusercontent.com/33039909/99227697-dfc59d80-27eb-11eb-8352-cbe348a290e0.png">

Does anyone know what could cause the problem?

Thanks!

**Comment by alexandrebodin** [comment]
Hi, 

Can you verify your package.json or  pacakge-lock.json is not pointing to an older version of the strapi-admin package ?

**Comment by sebqq** [comment]
<img width="699" alt="Screenshot 2020-11-16 at 15 03 03" src="https://user-images.githubusercontent.com/33039909/99261325-d6a0f480-281c-11eb-9a10-5835aeb6745e.png">
<img width="699" alt="Screenshot 2020-11-16 at 15 02 56" src="https://user-images.githubusercontent.com/33039909/99261334-d9034e80-281c-11eb-8f44-05edd5e7c954.png">

It looks like it is pointing to 3.3.2

**Comment by alexandrebodin** [comment]
Hey, I don't see anything wrong and I can't reproduce... are you using a volum with docker-compose or just docker run this image ?

**Comment by sebqq** [comment]
I'm using a combination of following two docker-compose files:

```docker
version: "3"
# docker-compose.yml

services:
  backend:
    container_name: container-strapi
    restart: unless-stopped
    networks:
      - strapi-app-network
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - db
    ports:
      - 1337:1337
    expose:
      - 1337

  db:
    image: mongo
    container_name: container-mongo
    networks:
      - strapi-app-network
    ports:
      - 27017:27017

networks:
  strapi-app-network:
    driver: bridge
```

and

```docker
version: "3"
# docker-compose.dev.yml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test

  db:
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - ./.test-db:/data/db
```

**Comment by sebqq** [comment]
Also, this picture is interesting

<img width="706" alt="Screenshot 2020-11-17 at 11 09 56" src="https://user-images.githubusercontent.com/33039909/99376687-8cc01900-28c5-11eb-96d1-10f16cd26206.png">

**Comment by alexandrebodin** [comment]
Hi, your 1st config will not use the image files but mount them so you will need to run a yarn build on the host. In your second conf it seems to me that it should work fine if you built the image previously :/

The screen shows that the api is in 3.3.3 and the admin in 3.3.2 and you upgraded the front from 3.2.2 to 3.3.2 by the way so you must have fixed something at some point :)

**Comment by sebqq** [comment]
@alexandrebodin I'm actually combining these two files using `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up` command. Shouldn't it combine these two yml configs into one?

**Comment by alexandrebodin** [comment]
I actually never used two docker compose config together :) Good to know !

So if it is actually used as one config then the volume mount overrides the build in the docker image and you still need to build the admin. I would suggest not to mount a volume if you already copy the files in the image.

**Comment by sebqq** [comment]
@alexandrebodin That seems to work 😺 thank you so much!
