### ISSUE TITLE
MacOS quickstart docker installation failed 

### ISSUE THREAD

**Issue by dgillier** [strapi/strapi-docker#268]
Hello,

I'm trying to install Strapi on OSX with no success.

I'm using the following docker-compose file :
```
version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
```

Did docker-compose pull then docker-compose up -d

But the container terminate itself after a few seconds...

docker logs strapi
```
Starting your app...
Building your admin UI with development configuration ...
ℹ Compiling Webpack
Error: Module not found: Error: Can't resolve './utils/filtersForm' in '/srv/app/.cache/plugins/strapi-plugin-upload/admin/src/components/FiltersPicker/FiltersCard'
    at /srv/app/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/srv/app/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/srv/app/node_modules/webpack/lib/Compiler.js:265:20)
    at /srv/app/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/srv/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /srv/app/node_modules/webpack/lib/Compilation.js:1173:13
    at /srv/app/node_modules/webpack/lib/Compilation.js:1096:25
    at /srv/app/node_modules/webpack/lib/Compilation.js:1017:13
    at /srv/app/node_modules/neo-async/async.js:2830:7
    at /srv/app/node_modules/neo-async/async.js:2830:7
    at done (/srv/app/node_modules/neo-async/async.js:2863:11)
    at /srv/app/node_modules/neo-async/async.js:2818:7
    at /srv/app/node_modules/webpack/lib/Compilation.js:1017:13
    at /srv/app/node_modules/neo-async/async.js:2830:7
    at /srv/app/node_modules/neo-async/async.js:2830:7
    at done (/srv/app/node_modules/neo-async/async.js:2863:11)
  ```

Got a few files installed :
Strapi/app/:
README.md	config		favicon.ico	package.json
api		extensions	node_modules	public

Any idea what's going wrong ?
Thanks for your help,
Denis

**Comment by alexandrebodin** [comment]
Hi @dgillier, let's try to find the issue :) 

Can you tell me a bit more about your setup.
- Did you already have a strapi application in the ./app folder you were trying to run ?
- What version of mac are you running on ? 
- Can you give me the output of `docker image inspect strapi/strapi -f {{.Config.Env}}`

**Comment by dgillier** [comment]
@alexandrebodin 
Thanks !

- No I don't have any app
- BigSur 11.1 on Intel
- ".Config.Env"

[
    {
        "Id": "sha256:44b51db1c3b06a0b38e5be35fb9ceb25880487518f8d08e32adef422041e8f1f",
        "RepoTags": [
            "strapi/strapi:latest"
        ],
        "RepoDigests": [
            "strapi/strapi@sha256:4f60623a8d53e8d6f7de247f95486654c9b54b4de41af9948d9fb47a25e9abfd"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-12-28T13:16:17.0973059Z",
        "Container": "4b9019fa78e940869d8cc700415cbbbfea662fe89f2641e7dff32b19fcbb13f0",
        "ContainerConfig": {
            "Hostname": "4b9019fa78e9",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1337/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=14.15.3",
                "YARN_VERSION=1.22.5"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"strapi\" \"develop\"]"
            ],
            "Image": "sha256:99609bbfae47d13c2c0998fc22abc3048b7c834fd02f8c1d1cfdcf61764d3f66",
            "Volumes": {
                "/srv/app": {}
            },
            "WorkingDir": "/srv/app",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "20.10.0",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1337/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=14.15.3",
                "YARN_VERSION=1.22.5"
            ],
            "Cmd": [
                "strapi",
                "develop"
            ],
            "Image": "sha256:99609bbfae47d13c2c0998fc22abc3048b7c834fd02f8c1d1cfdcf61764d3f66",
            "Volumes": {
                "/srv/app": {}
            },
            "WorkingDir": "/srv/app",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1023116372,
        "VirtualSize": 1023116372,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/9a1121747b6c7b27911130c164c3eee321a1600e2813a1dfd544f647873ca51a/diff:/var/lib/docker/overlay2/0e3b5160091f0fe769e067e1ae8aeda44648e94ee4da7389c5f2b86263de11a4/diff:/var/lib/docker/overlay2/462ef2cd63ef38d0912d6b4ccac3bad03612b330cdc6b1946470e445d91da9d2/diff:/var/lib/docker/overlay2/6a609069718db93a88e186127bb467cc3549737c0a221438aa79b359a16251a6/diff:/var/lib/docker/overlay2/23b0d5127aca7384e6262715d6e50a750493d06d151339f720b00e2a30fd8285/diff:/var/lib/docker/overlay2/74785a6113d03bbd8b097bec4f994a2fe600a91af870b7322d3dfc4f71d01e79/diff:/var/lib/docker/overlay2/1fea735803e3cfdaf821e0d70096ee8051c639a1927f12363917e3a547c42405/diff:/var/lib/docker/overlay2/c77856b67671e6a87c5b3f75cc9fb6dfb58208d0468fd61364ebe7066f1199a8/diff:/var/lib/docker/overlay2/37692418c61435eb9e26044ecd315ea63936d7c8ebe5c0e13cb1ef2d343acb0e/diff:/var/lib/docker/overlay2/18ceb9591425d48ac6428751389b8f90e2179480ff3cbe1985bb02a2d86c4b32/diff:/var/lib/docker/overlay2/c0b4cffa9e73b5f235fc43367002217912bbb46a1ab42b8208cfb3ba368273c7/diff",
                "MergedDir": "/var/lib/docker/overlay2/4ee196a8260cb09b9caee80912cf49b336b653f71bf18910800f6f5c88e30662/merged",
                "UpperDir": "/var/lib/docker/overlay2/4ee196a8260cb09b9caee80912cf49b336b653f71bf18910800f6f5c88e30662/diff",
                "WorkDir": "/var/lib/docker/overlay2/4ee196a8260cb09b9caee80912cf49b336b653f71bf18910800f6f5c88e30662/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:0279b13c6fc69327776f36c3e76faafb3d15dca370a91eefdd22641b2c50f257",
                "sha256:de1bb73bcb8b1510a25b52bed61cd13ec262df39e02b0cbdf9830bddd7edb8a8",
                "sha256:0a1c0b220d6e002ff35117e8badacac0548e974a0eaf1fc37a9a592aba9ab930",
                "sha256:8f82110acbe47306a09cdc1c4c23d286f50b8eb0de69b1ed4a1c0905f59c7f40",
                "sha256:75298d0cbb21ff5da354e37dcc6638896863e76340683a80ffb3fadf3cbce67b",
                "sha256:5a5c0a2eda051d78c47658ae2efc29f7f4549eb4ca3f34316105c40345ffa873",
                "sha256:9499c8f596a0c905497768a8bca5c04a0f3f86cb2722646ee2912281a3ad185c",
                "sha256:f92bc4578fac8c57a438824bdaae3ca757eeaa87e879b020965564b2f5c59986",
                "sha256:884645749ee7f943593083aaa7301d24ea6007497852fce88dccc2e6a886a461",
                "sha256:7bc0d0a30b8c96c3090919a82df6d1d10e4e086adcc60760caafa302b0cb6a4a",
                "sha256:041df025cd04effb6a1b96da50b5d0ac39731e07be6ca73304df47679cb0a21f",
                "sha256:a2b5c05ecdf970c442e624a0d8806af3730661f95ad882b2f1c38492aa4ddb86"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by alexandrebodin** [comment]
Thanks for the infos. Nothing looks wrong at first glance.

can you rm the app folder and retry so we know if it is always the same issue or not :)

**Comment by dgillier** [comment]
Did that and it's working like a charm now !
(Did not understand what happened...)

Anyway thanks for your help :)

**Comment by alexandrebodin** [comment]
I'm going to close the issue. If this happens again let us know !
