### ISSUE TITLE
Update image for 3.0.0-alpha.12.3 

### ISSUE THREAD

**Issue by alexleone** [strapi/strapi-docker#27]
Is it possible to get the repo updated to use strapi@3.0.0-alpha.12.3 ?

**Comment by alexleone** [comment]
Just noticed this pull request https://github.com/strapi/strapi-docker/pull/20 but seems odd the CI failed. I built and a custom image with it and seemed to work.

**Comment by jenseickmeyer** [comment]
I've created another Pull Request (#29) with an update to 3.0.0-alpha.12.4. I've also fixed the CI build.

@lucaperret can you please review whether this is a valid fix or if something else needs to be done. It would be great to have Docker images for Strapi again. Thanks.

**Comment by lucaperret** [comment]
Thanks, closed by #29.
