### ISSUE TITLE
Env URL is not working

### ISSUE THREAD

**Issue by kgnfth** [strapi/strapi-docker#273]
This is my Dockerfile

```Dockerfile
FROM strapi/base

WORKDIR /backend

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
```

All these env works

```
HOST
PORT
ADMIN_JWT_SECRET
DATABASE_HOST
DATABASE_PORT
DATABASE_NAME
DATABASE_USERNAME
DATABASE_PASSWORD
```
but this does not work
`URL=https://wefewf.wefwef.ef`

this is my default server.js file

```javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '72b949b5c9b1e31d62cc7f230c55aed5'),
    },
  },
  url: env('URL','https://api.example.com'),
});

```

i keep getting https://api.example.com

**Comment by alexandrebodin** [comment]
Hi, I don't se why but maybe URL is not a param w can set (I don't know why it woul) have you tried renaming to STRAPI_URL or example ?

**Comment by kgnfth** [comment]
Yes i tried it.

I followed this turorial @ https://strapi.io/blog/strapi-authentication-in-nuxt-js 
scroll down to `Configure Strapi's Server URL`

**Comment by alexandrebodin** [comment]
So you tried but did you get the right value with another variable name ? 

This value is used at build time too so maybe try to define your env var on the docker image build time too if you haven't.

**Comment by kgnfth** [comment]
i tried this

FROM strapi/base

WORKDIR /backend

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV production

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
