### ISSUE TITLE
Error getaddrinfo EAI_AGAIN postgres, when creating my own dockerfile

### ISSUE THREAD

**Issue by RaimonxDev** [strapi/strapi-docker#278]
Hi everyone, I have my application and I used the following example for Dockerfile.

![image](https://user-images.githubusercontent.com/39868803/108200559-647ecb00-70fd-11eb-8a5a-be6b77039d08.png)

then I try to build the image with Postgres databases and it gives me the following error

![image](https://user-images.githubusercontent.com/39868803/108200633-7b252200-70fd-11eb-8911-3be668d827a3.png)

here my docker-compose.

![image](https://user-images.githubusercontent.com/39868803/108200675-8f691f00-70fd-11eb-8c82-97edff9d7387.png)

Where am I making the mistake?
it is an app already built locally, I appreciate any help or guidance

**Comment by alexandrebodin** [comment]
Hi, how do you define your DATABASE_HOST ? is  it postgres2 (name of service) on your network ?

**Comment by RaimonxDev** [comment]
> Hi, how do you define your DATABASE_HOST ? is it postgres2 (name of service) on your network ?

OMG, of course. The value of .env had not changed .. Thank you very much. everything is resolved

**Comment by e1sep0** [comment]
Hi, but if i change .env variable, will can`t connect to DB in docker. How to resolve it ?
