### ISSUE TITLE
Is node 14 supported?

### ISSUE THREAD

**Issue by febbraro** [strapi/strapi-docker#283]
I noticed on Docker Hub that some version of the container (3.4.0 and 3.4.1) have node 14 versions, but in bin/constants.js it only mentions node 10 and 12 as build targets/

One of the reasons I am asking is that when using the SSO providers from the user-permissions extension that node 12on ly support 8k max header sizes (query string, cookies, etc) and node 14 supports 16k.  From AWS Cognito the id_token can be quite large and we got failures with node 12, but with node 14 and no other changes things worked.

Before I made a PR I just wanted to see if there was a specific reason that node 14 was supported? or if we should just add it to the build targets?

**Comment by atymchuk** [comment]
@alexandrebodin Could you please consider shipping node@14 by default instead of node@12 as the community seems to be asking for it since quite some time? If no resource available to do that, would you accept contributions to get thete?

**Comment by alexandrebodin** [comment]
Hi, Thanks for the notice, we were building the node 14 image from a fork with the updated constants and reverted without update the main repo. I'm testing that node 14 works and will push to make sure we release it correctly from now on.

**Comment by alexandrebodin** [comment]
Just tested and update the code. Starting with the next release node 14 will be included.
