### ISSUE TITLE
Shouldn't this docker image start in production mode?

### ISSUE THREAD

**Issue by Download** [strapi/strapi-docker#298]
Just looking at the code a bit to learn how to use this image, my eye got drawn towards this line:

_[strapi-docker/strapi/Dockerfile](https://github.com/strapi/strapi-docker/blob/8c052d610e61409697e4b4db6f7762dcd698e34f/strapi/Dockerfile#L16)_

```
CMD ["strapi", "develop"]
```

Shouldn't this image start in production mode? For me it's unexpected that this would start it in development mode.

**Comment by JamesAlexanderHill** [comment]
Strapi/strapi is for local development. If you want to run strapi in production mode via docker you will need to create your own image using strapi/base and a Dockerfile. This dockerfile can be referenced in a docker-compose.yaml for ease of use

**Comment by Download** [comment]
Looking at the README again I guess it actually says so on the tin.
Thanks for your response 👍

**Comment by JamesAlexanderHill** [comment]
If you want some examples on how to use strapi/base in production see the following folder: [here](https://github.com/strapi/strapi-docker/tree/master/examples)

Defs a good place to start
