### ISSUE TITLE
Any example on using mysql in the strapi-docker?

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi-docker#30]
Need example on using mysql in the strapi-docker.

**Comment by lucaperret** [comment]
Hello @demobo-com, you could change service `db` in the docker-compose file with a MySQL image, plus updating `DATABASE_CLIENT` api's environment to mysql.
It could be good to add it as an example in the README 🎉

**Comment by lauriejim** [comment]
Here is an example https://github.com/strapi/strapi-docker/pull/99

**Comment by frankxayachack** [comment]
I've created a repo of Strapi Docker using MySQL database you can just clone and edit some configs in docker-compose.yml then you are good to go
[https://github.com/frankxayachack/strapi-mysql-docker](url)
