### ISSUE TITLE
Provide v4-beta image

### ISSUE THREAD

**Issue by beyondmeat** [strapi/strapi-docker#315]

**Comment by ChristianHeimke** [comment]
node 16 (lts) won't be supported by strapi v3.x and will be used (maybe as default) for v4 as you can read here in the strapi issue: https://github.com/strapi/strapi/issues/11135

**Comment by ChristianHeimke** [comment]
only @beyondmeat can close it ;-)

**Comment by beyondmeat** [comment]
@ChristianHeimke please keep this updated until official is available.

**Comment by SupaMario123** [comment]
@ChristianHeimke first thank you for publishing! Do you have any idea why i get this error?
<img width="1007" alt="Bildschirmfoto 2021-12-07 um 13 24 37" src="https://user-images.githubusercontent.com/33687577/145028669-9783ccbc-826f-4f46-8c39-baced6a7b3c7.png">
<img width="963" alt="Bildschirmfoto 2021-12-07 um 13 24 42" src="https://user-images.githubusercontent.com/33687577/145028679-a2edba48-bb19-43f5-bdf2-2edae6b6d712.png">
