### ISSUE TITLE
docker-compose strapi : create app even code exist and double mount

### ISSUE THREAD

**Issue by tsv38** [strapi/strapi-docker#320]
When i want to run a strapi container with docker-compose and with a folder having already the code, log says that /svr/app is empty and create a new app. And when I check mounts, there are 2 mounts on /svr/app/.
If I create container with docker run -v `pwd`/strapi:/srv/app strapi/strapi it is ok, the app is just started.
**yml file like**
    volumes:
      - ./strapi:/svr/app
**mounts in inspect** 
"Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/c/Users/tsv/OneDrive/Dev/centrazen/strapi",
                "Destination": "/svr/app",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "1fc5b8dd03afcdbe9563b7d9bc33bb6d8fd783db5d05fecfd65727d51e2c7ae3",
                "Source": "/var/lib/docker/volumes/1fc5b8dd03afcdbe9563b7d9bc33bb6d8fd783db5d05fecfd65727d51e2c7ae3/_data",
                "Destination": "/srv/app",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],

**Comment by ChristianHeimke** [comment]
could you please provide the complete `docker-compose.yml` file? it is important which image you use (`strapi/base` or `strapi/strapi`).

**Comment by ChristianHeimke** [comment]
it looks like a typo in your compose file:
```
    volumes:
      - ./strapi:/svr/app
``` 

it should be:

``` 
    volumes:
      - ./strapi:/srv/app
``` 

you wrote `svr` instead of ` srv` - this could be the reason why the boot process is creating a new project. your docker run command `docker run -v pwd/strapi:/srv/app strapi/strapi` set the correct path on `/srv/app`.

**Comment by tsv38** [comment]
That's right. Many thanks. So many time just for a letter inversion. Best regards

**Comment by ChristianHeimke** [comment]
@tsv38 could you please close the issue if it's solved?
