### ISSUE TITLE
Error during docker run

### ISSUE THREAD

**Issue by dannydtk** [strapi/strapi-docker#38]
Hey,

I'm getting the following error after running default commands in README:
`Something else already exists at '/usr/src/api/strapi-app/node_modules'.`

Environment:
Amazon EC2  Amazon Linux AMI 2018.03
Docker version 18.03.1-ce, build 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3

Steps:
1. Run:
```
docker run -e MONGO_INITDB_DATABASE=strapi \
           -v `pwd`/db/:/data/db \
           --name strapi-mongo \
           -d mongo
```
2. Run:
```
docker run -e APP_NAME=strapi-app \
           -e DATABASE_CLIENT=mongo \
           -e DATABASE_HOST=strapi-mongo \
           -e DATABASE_PORT=27017 \
           -e DATABASE_NAME=strapi \
           -v `pwd`/strapi-app:/usr/src/api/strapi-app \
           -v /usr/src/api/strapi-app/node_modules \
           --link strapi-mongo:mongo \
           -p 1337:1337 \
           --name strapi -d strapi/strapi
```
3. `docker ps -a` shows that strapi container has exited
4. `docker logs strapi` output:
```
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
Database determined by CLI args: mongo

⏳ Testing database connection...
Something else already exists at '/usr/src/api/strapi-app/node_modules'.
```

These things don't help:
1. Removing the container `docker rm strapi`
2. Removing the container and the image `docker rm strapi` & `docker rmi strapi`
3. Running `docker system prune -a`

**Comment by lucaperret** [comment]
Hi @dannydtk,
It'll work if you remove the `node_modules` volume. Remove this line of your docker run:
`-v /usr/src/api/strapi-app/node_modules \`

**Comment by dannydtk** [comment]
It works, thank you. Anyway I've fixed the problem just by using docker-compose and your repository. Anyway I've got some other problem which I'm gonna report in another ticket.

**Comment by lucaperret** [comment]
I've changed the README.md for that, thanks!
