### ISSUE TITLE
Sync Docker Hub documentation with Github README

### ISSUE THREAD

**Issue by msgeissler** [strapi/strapi-docker#4]
I am not sure whether or not the [documentation on Docker Hub](https://hub.docker.com/r/strapi/strapi/) is somehow linked to the README.md here in github, but currently is has gotten out of sync.
Right now the differences are not critical or even that important but should probably be updated to the same version from time to time (unless there is an automatic way to achieve that).

**Comment by lucaperret** [comment]
Hi @msgeissler thank you for your comment.
@Aurelsicoko can you update the DockerHub image description with the content of the [README](https://github.com/strapi/strapi-docker/blob/master/README.md)

**Comment by msgeissler** [comment]
Using [automated builds](https://docs.docker.com/docker-hub/builds/#understand-the-build-process) the README could also be synced automatically.

**Comment by lucaperret** [comment]
Fixed by dd46bba4b933dc866fd2680a921b11a03b37814d 
Thanks for the work !
