### ISSUE TITLE
missing mongoose

### ISSUE THREAD

**Issue by jtktam** [strapi/strapi-docker#42]
I been trying to get the latest docker image to work.. it's failing with the following error (stack trace)

npm install strapi-hook-strapi-mongoose

**strapi_1  | [2018-08-10T11:00:37.463Z] warn (hook:strapi-mongoose) `strapi-hook-strapi-mongoose` is missing in your dependencies. Please run `npm install strapi-hook-strapi-mongoose`**
strapi_1  | error TypeError: strapi.models.core_store.forge is not a function
strapi_1  |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
strapi_1  |     at module.exports (/usr/src/api/strapi-app/plugins/content-manager/config/functions/bootstrap.js:156:42)
strapi_1  |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:285:13)
strapi_1  |     at new Promise (<anonymous>)
strapi_1  |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:273:11)
strapi_1  |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:44)
strapi_1  |     at Array.map (<anonymous>)
strapi_1  |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:35)
strapi_1  |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:107:18)
strapi_1  |     at <anonymous>
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
strapi_1  |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
strapi_1  |     at module.exports (/usr/src/api/strapi-app/plugins/settings-manager/config/functions/bootstrap.js:17:26)
strapi_1  |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:285:13)
strapi_1  |     at new Promise (<anonymous>)
strapi_1  |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:273:11)
strapi_1  |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:44)
strapi_1  |     at Array.map (<anonymous>)
strapi_1  |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:35)
strapi_1  |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:107:18)
strapi_1  |     at <anonymous>
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh
ich was not handled with .catch(). (rejection id: 7)
strapi_1  | (node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero ex
it code.
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
strapi_1  |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
strapi_1  |     at module.exports (/usr/src/api/strapi-app/plugins/users-permissions/config/functions/bootstrap.js:77:45)
strapi_1  |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:285:13)
strapi_1  |     at new Promise (<anonymous>)
strapi_1  |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:273:11)
strapi_1  |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:44)
strapi_1  |     at Array.map (<anonymous>)
strapi_1  |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:35)
strapi_1  |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:107:18)
strapi_1  |     at <anonymous>
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh
ich was not handled with .catch(). (rejection id: 8)
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
strapi_1  |     at fs.readdir (/usr/src/api/strapi-app/plugins/email/config/functions/bootstrap.js:53:40)
strapi_1  |     at <anonymous>
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh
ich was not handled with .catch(). (rejection id: 11)
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
strapi_1  |     at fs.readdir (/usr/src/api/strapi-app/plugins/upload/config/functions/bootstrap.js:55:40)
strapi_1  |     at <anonymous>
strapi_1  |     at process._tickCallback (internal/process/next_tick.js:182:7)
strapi_1  | (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise wh
ich was not handled with .catch(). (rejection id: 14)

**Comment by jakoblo** [comment]
same problem here... i just recreated the container with the newest strapi image

**Comment by lucaperret** [comment]
Hello, @lauriejim is it something related to the core?

**Comment by lauriejim** [comment]
@lucaperret I think it need an update somewhere since we move `strapi-mongoose` to `strapi-hook-mongoose`.

I think a dependencies has not been changed.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.

**Comment by asotoglez** [comment]
any solution?
