### ISSUE TITLE
Unable To Debug

### ISSUE THREAD

**Issue by mikepuglisi** [strapi/strapi-docker#43]
I would like to develop within the docker container while being able to setbreak points and inspect in vscode.

I typically accomplish this by passing the --inspect flag for the startup process.

    "start": "node --inspect=0.0.0.0:9222 server.js",

Unfortunately, I'm having a hard time understanding how to apply this concept to this project....

Can someone explain how I can debug strapi in vscode while running in a docker container?

**Comment by lucaperret** [comment]
Hello @mikepuglisi, please try to bind ports in the docker-compose file like [this tutorial](https://blog.risingstack.com/how-to-debug-a-node-js-app-in-a-docker-container/)

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
