### ISSUE TITLE
cannot start container strapi:latest

### ISSUE THREAD

**Issue by matteo-bombelli** [strapi/strapi-docker#48]
Hello I tryed to run strapi + mongodb on docker (making them run from portainer) but it crashes at start

ENV parameters:

parameter | value
------------------ | ---------- 
DATABASE_CLIENT | MongoDB
DATABASE_HOST | mongodb_strapi
DATABASE_USERNAME	| *****
DATABASE_PASSWORD	| *****
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION | 9.11.1
YARN_VERSION | 1.5.1
DATABASE_NAME | strapi
DATABASE_PORT | 27017
DATABASE_SSL | false

error from docker logs:

```
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️
Lets configurate the connection to your database:
Database determined by CLI args: MongoDB
(node:6) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at inquirer.prompt.then.answers (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:111:53)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
./strapi.sh: cd: line 28: can't cd to strapi-app
```

docker engine version:

parameter | value
-- | --
Version | 18.06.0-ce
API version | 1.38
Go version | go1.10.3
OS type | linux
OS | Ubuntu 16.04.5 LTS
Architecture | amd64
Kernel version | 4.13.0-1012-gcp

thank you!

**Comment by lucaperret** [comment]
Your `DATABASE_CLIENT` environment variable should be one of:
- mongo
- postgres
- mysql

**Comment by BlackDark** [comment]
Same here:
Attaching to strapi_api_1
api_1  | 🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️
api_1  |
api_1  | Lets configurate the connection to your database:
api_1  | Database determined by CLI args: mongo
api_1  |
api_1  | ⏳ Testing database connection...
api_1  | { Error: Cannot find module '/tmp/strapie0ea507fb540/node_modules/strapi-hook-mongoose/lib/utils/connectivity.js'
api_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
api_1  |     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
api_1  |     at Module.require (internal/modules/cjs/loader.js:598:17)
api_1  |     at require (internal/modules/cjs/helpers.js:11:18)
api_1  |     at Promise.all.then (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:259:15)
api_1  |     at <anonymous> code: 'MODULE_NOT_FOUND' }

**Comment by rabira-hierpa** [comment]
I had the same issue but without docker and` yarn global add strapi@alpha` solved my problem
:smile:

**Comment by lauriejim** [comment]
Don't use yarn with Strapi, not fully supported.

**Comment by maxime1992** [comment]
Migrating strapi from dev to prod... Is sooooooo complicated. Cannot migrate db, containers are crashing when restarted... I know it's not useful to complain but after building a project using it I definitely regret not trying to put everything on prod at the beginning. I do feel completely stuck now :fearful:

**Comment by lauriejim** [comment]
Hello @maxime1992 !
Thank you for this message, we know we have some hard work to do to make the switch easy as it's easy to build your API.
There is a ticket in our roadmap - https://portal.productboard.com/strapi/c/12-migrate-across-environments - feel free to add a comment to help us to build this feature the better we can.

**Comment by maxime1992** [comment]
> we know we have some hard work to do to make the switch easy as it's easy to build your API

I wish you guys the best and Strapi looks very promising :raised_hands:.

Might just be worth mentioning the state of Strapi on Github so that people knows what to expect for now :) 

But keep up the good work :muscle: :clap:

**Comment by lauriejim** [comment]
Thank you @maxime1992 ! We are doing our best to have to best product with the best community!

**Comment by oxnxo** [comment]
@matteo-bombelli , @BlackDark were you able to solve the problem?
I also just installed a fresh instance of mongo and strapi. I'm getting the same database connection error 
Testing database connection...
⚠️  Database connection has failed! Make sure your database is running.

My database is running as i've been able to connect to it using navicat.
Env variables 
PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION:11.1.0
YARN_VERSION:1.12.1
DATABASE_HOST:localhost
DATABASE_PORT:32818
DATABASE_CLIENT:mongo
DATABASE_NAME:strapi

My docker Port is 27017 

What could I be doing wrong? I've searched everywhere online. Kindly assist.

**Comment by Guillaume175** [comment]
@rabira-hierpa Comment as-tu résolu ton probléme ? j'ai le meme souci de connexion... utilises-tu Portainer pour administer tes containers ?

**Comment by lauriejim** [comment]
@Guillaume175 can you post/edit your message in english please.

**Comment by lauriejim** [comment]
Can you give us an update please.
Based on last version of files.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯

**Comment by SwathyRajeev** [comment]
Is that possible to connect strapi with mariadb?

**Comment by lauriejim** [comment]
Yap! You will have to use the same config as a MySQL database.
But you set the HOST and PORT of your MariaDB database.
It's because it uses the same driver as MySQL
