### ISSUE TITLE
Arm Friendly docker compose

### ISSUE THREAD

**Issue by guushamann** [strapi/strapi-docker#50]
Hi,

not an issue, but did not know where to put this

check my ARM friendly docker build files
tested on raspberry pi 3+ with hypriot image (https://blog.hypriot.com/)

[https://gist.github.com/guushamann/6fec5c073e2edb6579e8060e7e7f3bd9](url)

cheers,
Guus

**Comment by lauriejim** [comment]
The link is not correct.

**Comment by guushamann** [comment]
Hi , do not know why, but here is the link to the gist

https://gist.github.com/guushamann/6fec5c073e2edb6579e8060e7e7f3bd9
