### ISSUE TITLE
Third party database hosting - mongodb

### ISSUE THREAD

**Issue by rodrigoWollies** [strapi/strapi-docker#52]
Hi Guys,

I'm looking to use mlab or mongo atlas to host the database. Our current strapi app is running locally, we are trying to dockerise it but cannot get it to connect to hosted database. Any ideas?

Cheers, Rodrigo

**Comment by lucaperret** [comment]
Hi @rodrigoWollies , Could you paste your dockerfile or docker-compose, please.

**Comment by lvnilesh** [comment]
I could not locate a way to specify `? +srv connection: true`

Need a docker-compose ENV to set this. 
```
scope.database.settings.srv 
```
