### ISSUE TITLE
node version?

### ISSUE THREAD

**Issue by caoer** [strapi/strapi-docker#57]
![image](https://user-images.githubusercontent.com/225856/46167234-db665f80-c2c7-11e8-8c8e-fe32f4024bfb.png)

strapi's node version requirement is >= 10.x. why are we using `FROM node:9.11.1-alpine` ?

**Comment by lucaperret** [comment]
Hi,
because https://github.com/strapi/strapi/blob/master/package.json#L64
specify version >= 9 for now.

**Comment by caoer** [comment]
I see, got it. thanks.
