### ISSUE TITLE
installed version is 14.0 but installer is 14.2

### ISSUE THREAD

**Issue by rejifald** [strapi/strapi-docker#58]
Somehow, after i run "docker-compose up", everything installs and starts, but powered by strapi 14 version. This is critical, because on this version creating new content type via GUI is impossible. And many other things not working.

**Comment by lucaperret** [comment]
The actual version is v3.0.0-alpha.14.2, is this issue related to the docker image ?

**Comment by MoQ93** [comment]
This is possible related to https://github.com/strapi/strapi/issues/2011?

**Comment by rejifald** [comment]
@MoQ93 @lucaperret thank you for response. Problem were with docker container. Another strapi docker was ran in background. So every time i did see another strapi instance.
I think this issue because when i did run container, it did output in log that everything is ok.
But certain port has been already allocated by another strapi instance
