### ISSUE TITLE
What to save on Git?

### ISSUE THREAD

**Issue by GlennCarroy** [strapi/strapi-docker#60]
Hey there,

I am curently using a docker-compose containing the official images used to make strapi run.

I would like to know which folders have to be saved on github when you want to commit your code?

For now, after some research, it looks llike everything (all folders) are pushed, which might get pretty heavy with a project growing up, is there a reason for that? Cannot the admin / functionnal part not be pushed while commiting since the docker-compose will rebuild everything anyway?

Thank you in advance for your answers!

**Comment by lauriejim** [comment]
The rebuild is different than the update version.
So to keep your project consistence by the version of all dependencies (admin, plugins) we have to commit them.
As you can customise these parts you will have to same it.
