### ISSUE TITLE
User role selection results in blank page

### ISSUE THREAD

**Issue by amitmalagi** [strapi/strapi-docker#61]
**Informations**
- **Node.js version**: 
- **npm version**: 
- **Strapi version**:  v3.0.0-alpha.14.3 using docker-compose
- **Database**: 
- **Operating system**: Ubuntu

**What is the current behavior?**
Clicking on role selection takes user to blank page.

**Steps to reproduce the problem**
Install Strapi using docker-compose. Register new user as admin and sign-in. Click on 'add new user' and click on role selection. Opens blank page.

**What is the expected behavior?**
User should be allowed to selected one of the available roles.

**Suggested solutions**

**Comment by jackstrapp** [comment]
I can reproduce this issue on the 'add content type' page. 
![image](https://user-images.githubusercontent.com/12911863/47946925-2f78eb00-dee9-11e8-923c-eb20ca9fee90.png)

**Comment by lauriejim** [comment]
@jackstrapp also using Docker ?

**Comment by jackstrapp** [comment]
Yes also docker but only with this repo. I tried a simple custom install kind of like this one and everything works as expected:
```
FROM node:8

RUN npm install -g strapi@alpha

RUN strapi -v

EXPOSE 1337

WORKDIR /
RUN strapi new strapi-test --dbclient=mongo --dbhost=%mongoIp% --dbport=%mongoport% --dbname=strapi-test-docker --dbusername= --dbpassword --dbauth=
WORKDIR /strapi-test
CMD ["strapi", "start"]
```

**Comment by rolandbough** [comment]
Thanks for the tip I will give that a shot.

-Ro

**Comment by lauriejim** [comment]
Okay thank you for this details

**Comment by jackstrapp** [comment]
Tested a clean
```
git clone ..
docker-compose up
```
on an ubuntu docker host and it works like a charm 🥇 

Thanks
