### ISSUE TITLE
Lato font not loading

### ISSUE THREAD

**Issue by donaldr** [strapi/strapi-docker#69]
**Informations**
- **Node.js version**:  v9.11.1 (from the docker instance strapi/strapi)
- **npm version**: 5.6.0 (as installed by docker instance)
- **Strapi version**: 3.0.0-alpha.14.3

Lato font not loaded when running strapi from docker instance. Many pages have a sans serif font.

**Comment by lucaperret** [comment]
Could you try with the last image release ?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
