### ISSUE TITLE
/admin path not loading correctly with nginx reverse_proxy

### ISSUE THREAD

**Issue by benjbaron** [strapi/strapi-docker#73]
Hello, 

I have been trying to setup the Docker containter of Strapi behind a nginx reverse proxy. The Docker container is configured as follows: 
```

docker run -e APP_NAME=strapi-app \
               -e DATABASE_CLIENT=mongo \
               -e DATABASE_HOST=XXX \
               -e DATABASE_PORT=27017 \
               -e DATABASE_NAME=strapi \
               -v `pwd`/strapi-app:/usr/src/api/strapi-app \
               -p 8004:1337 \
               --name strapi -d strapi/strapi
```

And the configuration of the nginx server is the following: 

```
location /strapi/ {
            allow all;
            proxy_http_version 1.1;
            proxy_set_header  X-Forwarded-For    $proxy_add_x_forwarded_for;
            proxy_set_header  Host               $http_host;
            proxy_set_header  X-Real-IP          $remote_addr;
            proxy_set_header  X-Forwarded-Proto  $scheme;
            proxy_set_header Accept-Encoding "";
            proxy_pass http://127.0.0.1:8004/;

            ModSecurityEnabled on;
            ModSecurityConfig modsec_includes.conf;
}
```

When I go to `https://my.domain.co/path/to/strapi/`, I can see the welcome page but when I try to go to the admin page at `https://my.domain.co/path/to/strapi/admin/`, the base `index.html` page loads by the resources, including `/admin/main.js` do not load since they refer to the path `https://my.domain.co/admin/main.js`, which omits the `path/to/` part of it.

I have been trying a hacky way to rewrite the url of the resources from the nginx configuration as follows: 
```
sub_filter_types *;
sub_filter '/admin/'  '';
sub_filter_once off;
```
This enables the page `https://my.domain.co/path/to/strapi/admin/` to load the `main.js` resource but there are many other files referenced in the `main.js` whose uri does not get re-written, mainly because of the Javascript concatenations that are used in the script. 

As such, I was wondering if there is a better way to enable Strapi behind a nginx reverse proxy.

Thank you in advance.

**Comment by COcis-io** [comment]
Same here!

**Comment by MatteoGioioso** [comment]
Same issue either with subfolder or subdomain

**Comment by MatteoGioioso** [comment]
Ok, after 2 days I have solved it 🙏 .

Make sure on the docker-compose to change this environment key:
in my case I make it work through sub-domain, but I think it should work without a subdomain

```
 api:
    build: strapi/
    environment:
      - HOST=www.subdomain.yourdomain.com <-- change this to your host
      - NODE_ENV=production
    volumes:
```

and then in your strapi config `server.json`

```
{
  "host": "www.subdomain.yourdomain.com", <-- change to your host
  "port": "${process.env.PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": false
  },
 ...
```
