### ISSUE TITLE
Hot Replacement (Stateless) Containers

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi-docker#83]
Hello!

Currently, the container installs itself when starting. This should be actually done **during the image build step**, not when running the container.

### The Problem

The setup right now, does not allow to quickly switch environment variables because they are only read when setting up the container. Any other reconfiguration of the container that is not doable during runtime ( change exposed ports, add labels for docker reverse proxy, set volumes) has to trigger the reinstallation of strapi.

![image](https://user-images.githubusercontent.com/2950505/51183055-6cd9fb80-18d0-11e9-8bc8-14f6ac860d05.png)
(Source: https://robin.io/blog/stateless-vs-stateful-containers-1/)

### The Solution

To make a docker app stateless, it has to consider its lifecycle. I already talked about that here: https://github.com/strapi/strapi/issues/1763

If all initial dependencies required for the runtime are managed during `docker build`, and additional packages can be installed during runtime - by using a volume - the startup time can be cut down to virtually zero.

I work around this problem right now, by installing all plugins in `build`.
This works, if you check in a project created by `strapi init`.

I let plugins and admin panel only be downloaded when needed and `uploads` is embedded as volume.

Thus I have the following files in my `.gitignore` file:
``` .gitignore
**/build
admin
/plugins
uploads
documentation/
```

This is the dockerfile:

``` Dockerfile
FROM strapi/strapi

WORKDIR /usr/src/api/app

# Copy from strapi initialized project root
COPY package* ./

RUN npm install

RUN ln -s node_modules/strapi-admin admin

RUN strapi install content-manager
RUN strapi install content-type-builder
RUN strapi install email
RUN strapi install graphql
RUN strapi install settings-manager
RUN strapi install upload
RUN strapi install users-permissions

COPY public ./public

WORKDIR ./public
RUN npm install
RUN npm run build

# Cleanup and overwrite of plugin data

WORKDIR /usr/src/api/app
COPY server.js ./
COPY api ./api
COPY User.settings.json ./plugins/users-permissions/models

COPY config ./config
COPY ./favicon.ico ./favicon.ico

EXPOSE 1337

ENV NODE_ENV production

CMD "npm start"
```

**Problems**

There are a few changes required to make this work. Installing the plugins as part of the build cycle is not optimal. Ideally you would have a `strapi.json` (like package.json) or something like that, to tell what plugins need to be installed. This should be a volume and can be used to deal with consecutive installs.

Plugins - in the best case - should also be stateless and not require something like a User json to be copied to some plugin folder.

### Conclusion

The deployment mechanisms of strapi and docker are a bit different. For Docker it doesn't make sense to have three environments configured. At least from a DB connection point of view. Instead it would make sense to define connections to other containers (DB) as environemt variables that are either saved to the configuration or read during runtime.

Please let me know what you think, and what your experience is.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
