### ISSUE TITLE
quickstart on Mac OSX not working

### ISSUE THREAD

**Issue by joelbqz** [strapi/strapi-docker#89]
![image](https://user-images.githubusercontent.com/19965325/51791042-3f603e00-216b-11e9-9dbc-8d5f1fa04283.png)

`exception in initAndListen: IllegalOperation: Attempted to create a lock file on a read-only directory: /data/db, terminating`

` Database connection has failed! Make sure your database is running.`

How can I fix this issue? I'm using quickstart on Mac OSX

Thank you!!

**Comment by msgeissler** [comment]
That is most likely a problem with the permissions, if you are using the docker-compose.yml from this repo. https://hub.docker.com/_/mongo -> Scroll down to Caveats -> Where to Store Data
 and read the warning

The current version of the docker-compose.yml (which really should be used only by the CI connected to the github repo to do tests) mounts a db-folder from the host system to store the database data, this can cause a bunch of problems (I had those on Windows as well):
```
    volumes:
      - ./db:/data/db
```

For Windows and Mac OSX you will have to switch to docker volumes for mongodb.

**Comment by lauriejim** [comment]
Can you give us an update please.
Based on last version of files.

**Comment by cchew** [comment]
If anyone else is having issues with Quickstart on MacOS:

```
sudo mkdir -p /data/db/strapi
sudo chown -R $USER /data/db/strapi
```

This will create a folder off your `/User` folder (which is what was causing the issue for me). Then update `docker-compose.yaml` under `'db'`:

```
    volumes:
      - /data/db/strapi:/data/db
```

Then run `docker-compose up`.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
