### ISSUE TITLE
Connection to api service

### ISSUE THREAD

**Issue by nan140114** [strapi/strapi-docker#93]
Usually**, docker containers can be accesed via `docker exec -it container_name /bin/bash`  or via composer with `docker-compose exec service_name /bin/bash` . Sometimes you need to connect to container for inspect some data or files. In this case `api` only have the shell interpreter available. Would have sense to update the README file for advise the user that they can use [1] and [2] commands for connect to `api` service/container?

 [1]  `docker exec -it container_name /bin/sh`
 [2]  `docker-compose exec service_name /bin/sh`  

** It depends on the image, it's not applies for all docker images.

**Comment by lauriejim** [comment]
I think it's related to docker documentation and not specific to Strapi.
But it can useful to have this information quickly when you start with Strapi docker.
Feel free to submit a PR!
