### ISSUE TITLE
How to use nginx in strapi-docker?

### ISSUE THREAD

**Issue by mastermsd** [strapi/strapi-docker#94]
Hello,

I have been trying to setup the Docker containter of Strapi behind a nginx reverse proxy, because I'm having trouble with adding new users ([#2472](https://github.com/strapi/strapi/issues/2472), [#2424](https://github.com/strapi/strapi/issues/2424))
But somehow I can't get it to work.
The file structure is as follows: [mastermsd/strapi-docker](https://github.com/mastermsd/strapi-docker). And I don't have much experience with nginx.
Any help is much appreciated!

**Comment by zakthompson** [comment]
I'm having exactly the same issue with nginx-ingress in a DigitalOcean Kubernetes cluster - white screen when trying to create a new user.  I've tried the solutions presented in [#2424](https://github.com/strapi/strapi/issues/2424) but the issue persists, and I'm wondering if it could possibly be related to the dockerized version specifically

**Comment by botzill** [comment]
Hi @zakthompson, I have the same setup as you and have the same issue, did you manage to find a solution?

Thx!

**Comment by zakthompson** [comment]
@botzill Yes, that's how I set the headers, and the `X-Forwarded-Host` header is showing in my requests after adding that.  Nonetheless, the response is still masked and I still get the white screen.  Haven't found a solution yet

**Comment by botzill** [comment]
I see. Thx @zakthompson. 

Let's see if we find a solution here.

**Comment by shnigi** [comment]
Getting the same error.

**Comment by shnigi** [comment]
Solved in our project: proxy headers problem in kubernetes ingress-nginx was to add a ConfigMap to the ingress-nginx service (in ingress-nginx namespace):

```data:
  use-forwarded-headers: "true"
kind: ConfigMap
metadata:
  name: nginx-configuration

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
