### ISSUE TITLE
Add option for --dbforce

### ISSUE THREAD

**Issue by botzill** [strapi/strapi-docker#95]
Hi.

Will be great to have this option as well for the cases when we run it automatically, like kubernetes cluster. Now it's asking for user input if app exists. Havig `dbforce` can solve this issue.

Thx!

**Comment by lauriejim** [comment]
Feel free to submit a PR to add this feature.
We will appreciate your contribution on this issue.

**Comment by botzill** [comment]
Already did a PR for this: https://github.com/strapi/strapi-docker/pull/96. We can close this one.

**Comment by lauriejim** [comment]
Perfect, thank you!
