### ISSUE TITLE
Relax healthcheck

### ISSUE THREAD

**Issue by githubsaturn** [strapi/strapi-docker#97]
There are 2 problems with healthcheck:

- it kicks in only after 30sec. On slower systems, the app creation process takes longer and it causes continuous crashing. This should be changed to 1min.
- it relies on `localhost` DNS resolution, it may cause problems on systems with multiple network interfaces. This should be changed to `127.0.0.1`. (this is not as critical as the first issue, but it's a good practice)

There are reports of multiple restarts:
https://github.com/caprover/caprover/issues/376#issuecomment-467118076

This indeed the healthcheck issue. As you can see in the thread, I removed the healthcheck and it is now working according to the other users in the thread.

**Comment by lauriejim** [comment]
This is due to the software you use, the health check have to be used when the app is started and not during the creation process 🤔

**Comment by githubsaturn** [comment]
I agree. The health check should not kick in during the strapi creation. Health-check, however, is part of the docker image. Docker image is already created when the Strapi app is being created. 

This is a problem with the way health-check is defined in the docker file.

**Comment by lauriejim** [comment]
Ho okay. Feel free to investigate and submit a PR.
We are focus on other topic (main focus on the strapi/strapi repo)

**Comment by lauriejim** [comment]
We will appreciate your contribution on this issue.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
